### ISSUE TITLE
getMeteorData does not work with findOne

### ISSUE THREAD

**Issue by lentan1029** [meteor/react-packages#101]
throws error "Cannot read property "url" of undefined.
Exception from Tracker recompute function:
debug.js:41 TypeError: Cannot read property '_currentElement' of null"

The very same code works if I use post = find().fetch() and this.data.post[0].

**Comment by giantelk** [comment]
Works for me. Can you post your code, to reproduce this. Ideally upload a Meteor project to your github account with just the barebones code to reproduce the bug. See here: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor

**Comment by lentan1029** [comment]
https://github.com/lentan1029/testreactmeteor

It seems that you cannot pass findOne() data from getMeteorData into the prop of another component, but you can do so for find()

**Comment by giantelk** [comment]
Looks like you need to include the package `flow router`, along with code to specify your route(s) and actions. Pretty sure in the line below `content` is NOT part of `react-layout` but a `flow-router` feature.

`ReactLayout.render(Main, {content: <AltHome />})`

Flow-router says to include {this.props.content} in the render of your Main component, as per the instructions here for *Using as a Layout Manager*:
https://atmospherejs.com/kadira/react-layout

**Comment by lentan1029** [comment]
ok thank you i'll open the issue in flow router
