### ISSUE TITLE
meteor update error

### ISSUE THREAD

**Issue by Maiti** [meteor/react-packages#105]
In the react-todos example:
$ meteor update
This project is already at Meteor 1.2-rc.7, which is newer than the latest
release.
=> Errors while upgrading packages:           
                                              
While selecting package versions:
error: unknown package: isobuild:compiler-plugin
Required by: meteor 1.1.7-rc.1
Required by: less 2.5.0-rc.2_1
Required by: ecmascript 0.1.3-rc.1
Required by: jsx 0.2.0
Required by: coffeescript 1.0.8-rc.2
Required by: static-html 1.0.0-rc.3

unknown package: isobuild:isopack-2
Required by: ecmascript 0.1.3-rc.1
Required by: caching-compiler 1.0.0-rc.0
Required by: ddp-server 1.2.1-rc.1
Required by: accounts-base 1.2.1-rc.1
Required by: react-meteor-data 0.1.7
Required by: templating-tools 1.0.0-rc.0
Required by: caching-html-compiler 1.0.1-rc.0
Required by: react-meteor-data 0.1.7

**Comment by stubailo** [comment]
Try RC 12?

**Comment by Maiti** [comment]
$ meteor --version
Meteor 1.2-rc.7

**Comment by dgreensp** [comment]
This bug affects `meteor update` with no arguments, and is fixed in 1.2-rc.12: https://github.com/meteor/meteor/issues/5054

To update to 1.2-rc.12, use:

```
meteor update --release METEOR@1.2-rc.12
```

**Comment by Maiti** [comment]
Thanks
