### ISSUE TITLE
[bug with react?] Images lock up browser, 100% CPU.

### ISSUE THREAD

**Issue by trusktr** [meteor/react-packages#109]
I was using Meteor's official `react` package, and I had some Image elements that were being inserted into Famous components, something like

```js
                <Node id="backgroundRoad"
                    sizeMode = {['relative','relative']}
                    proportionalSize = {[1,1]}
                    align = {[0.5,0.5]}
                    mountPoint = {[0.5,0.5]}
                    opacity = {0.15}
                    position = {[0,0,1]} >

                    <DOMElement>
                        <img src={"http://d1hmbd9q8ooo7p.cloudfront.net/mobile/road.jpg"} style={{height: '100%', width: '100%'}}/>
                    </DOMElement>

                </Node>
```

and it was causing the browser tab (in Google Chrome) to lock and and freeze, with 100% CPU usage. I've no idea why.

To fix the problem, I removed the `react` package and I compiled my fork of [react-famous](https://github.com/trusktr/react-famous/tree/joe) which uses React `^0.13.1`, which will pull the latest 0.13.x version, which is 0.13.3 I believe.

That version is (supposedly) not different from the version that is in the official Meteor `react` package, so I don't know why using the one I compiled (my fork of react-famous attaches it's `React` to `window`) works, and using Meteor's doesn't.

The only thing in common between using the `react` package or not, is that I'm using the `react-meteor-data` package for reactivity. I would think that `react-meteor-data` doesn't pull in `react-runtime`, but if it does, then my compiled React overrides that one.

**Comment by stubailo** [comment]
You're right - `react-meteor-data` doesn't include `react-runtime`, so you can use it with a custom react if you want.

I can't think of any reasons why any of the things you're describing would cause 100% CPU usage in Chrome.

Any ideas? Have you tried using Chrome's profiler to see what is using the CPU?

**Comment by stubailo** [comment]
I can't figure out what would cause this for images, and there isn't a reproduction that I can run. Closing the issue.
