### ISSUE TITLE
Warning: render() is not reactive (I don't understand)

### ISSUE THREAD

**Issue by CodeOfDavid** [meteor/react-packages#110]
From your documentation...

"Warning: render() is not reactive

If you access a Meteor reactive data source from your component's render method, the component will not automatically rerender when data changes. If you want your component to rerender with the most up-to-date data, access all reactive functions from inside the getMeteorData method."

I don't understand "access all reactive functions from inside the getMeteorData method." I am making changes to this.data but the UI is not changing, how can I make the UI update when setting this.data?

Also just to add what Im trying to do is load a document from meteor, then in the UI make changes to "first name" and "last name" have a computed field called "full name" produced through a function, then later the user presses the 'Save' button and all the data is saved to meteor. (In my case 'full name' is also saved, but there will be other computed field which are not saved)

**Comment by giantelk** [comment]
Use this.data inside the render method. I.e.

render() {
   return {this.data.something};
}

Check out the examples.

**Comment by CodeOfDavid** [comment]
I do use this, however when I set this.data.something="abc" in code the UI render {this.data.post.something} does not update

**Comment by CodeOfDavid** [comment]
Ive seen a possible answer is to use a sub component

**Comment by bwhitty** [comment]
I'm not sure if I understand completely what you are doing, but treat `this.data` like `this.state` in that do not mutate it directly. For example, the way to update `this.data` is to *return an object* from the `getMeteorData` method. That is what is meant by the error "access all reactive functions from inside the getMeteorData method".  If you are just doing `this.data = 123` in a random method in your component, then whenever `getMeteorData` runs, that value will be overwritten by whatever is returned.

**Comment by CodeOfDavid** [comment]
I understand its correct to return a new object, I'm my code I return   

 return {
      ready: post.ready(),
      post: postInstance
    };

within  getMeteorData() {

the returned "post" (see above) has a property called "text", I then have a {this.data.post.text} handlebar output in my render together with a textbox that calls an onChange  event which updates this.data.post.text

However when this.data.post.text gets updated the UI does not change i.e. {this.data.post.text} does not re-render to show the new value [which was entered into the textbox]. 

Ive read that perhaps I should have a control which loads the data through getmeteordata then on render calls another react class which is renders the control using values from getInitialState. getIntialState will load through props the post

Although (due to my being new to this) I cant see why I cant have reactive 2 way binding straight from the getMeteorData returned Post object. I will submit to this subcomponent logic if people here tell me to use a component with a subComponent.

**Comment by CodeOfDavid** [comment]
@bwhitty I understand that the data could be overwritten from meteor but ill put checks in the getMeteorData method to ensure this does not happen.

**Comment by bwhitty** [comment]
You should not update `this.data.post.text` in your `onChange` handler. Assuming that a `post` is a Mongo / reactive source of some sort, in your `onChange` handler you should do `Posts.update({text: "new data"})`. What this will then do is cause `getMeteorData` to re-run, and your new `Post` data will then flow back down through that method and your UI will update as expected.

The key is to treat `this.data` like you would `this.state`. Do not modify it directly, but instead allow your reactive data sources to update it from within `getMeteorData`.

**Comment by CodeOfDavid** [comment]
Posts.update({text: "new data"}) would cause the record to be saved in the database. What I am doing is opening a form allowing the user to make a bunch of changes to the fields in the form. Some fields are computed (fullName = firstName + ' ' + lastName) then when the user clicks the Save button I call update. Until then I would like computed fields to change as the user types.

**Comment by bwhitty** [comment]
For working with form data, I'd recommend reading up on using forms from within React. https://facebook.github.io/react/docs/forms.html

**Comment by CodeOfDavid** [comment]
Thanks. I got it all working. I made a sub control and used it state
