### ISSUE TITLE
using server method call in ReactMeteorData

### ISSUE THREAD

**Issue by vraptor75011** [meteor/react-packages#114]
I'm trying to use the return value of a server method call from the client inside getMeteorData() like this

```javascript
Demo = React.createClass({
    mixins: [ReactMeteorData],
    getMeteorData() {
        var data = {};
        var self=this;
        Meteor.call("checkOrInviteUser",this.state.useremail, function(error,result){
            console.log(result);  // i get the expected value
            data.checkuseremail = result;
        });
        return data
    },
    render() {
        console.log(this.data); // always undefined
        return (<div/>)
    }
```

this.data is always undefined. 

What would be a correct way to handle this ?

**Comment by eXon** [comment]
You shouldn't use ReactMeteorData. You should make your call in componentWillMount and use the setState. getMeteorData is for reactive variables like subscriptions.

**Comment by vraptor75011** [comment]
That's what I did and it worked fine.
Thks
