### ISSUE TITLE
Upgrade to React 0.14

### ISSUE THREAD

**Issue by stubailo** [meteor/react-packages#116]
http://facebook.github.io/react/blog/2015/10/07/react-v0.14.html

We need to get on top of this! That includes updating examples, etc.

**Comment by andreasbhansen** [comment]
Yes please! :+1:

**Comment by bwhitty** [comment]
I see that the Meteor package versions are tracking React versions, but I'm not sure this makes sense for Meteor. I think the dev/prod runtime packages should probably be bumped to 1.0, and when an update to React 0.14 is pushed, bump them to 2.0 because there are breaking changes introduced in React 0.14. Thoughts?

**Comment by stubailo** [comment]
I think this would be more confusing than helpful - how would you even find out which features of React are available in "Meteor React" version 3.1.4? It could be 0.15, or 1.2, or anything else.

**Comment by bwhitty** [comment]
I guess what I'm really getting at is if the `react` package is updated to React `0.14` and I run a `meteor update`, am I going to unwittingly get BC breaks because this package isn't technically SemVer?

**Comment by stubailo** [comment]
Yep, that's correct. @dgreensp what do you think about this issue?

**Comment by dgreensp** [comment]
Using different major versions would create more problems than it would solve, because of packages that depend on `react`.  Different major versions are considered completely incompatible, so the likely result is that people would be stuck not able to run their apps at all.  Whereas if people get deprecation warnings and errors, at least they can update their apps and pressure packages to update upstream.

**Comment by okada** [comment]
+1

**Comment by v3rron** [comment]
+1

**Comment by ffxsam** [comment]
Isn't it possible for package authors to pin their package at a specific version? So couldn't you just pin `react` at 0.1.13, so in order for people to update that package, they have to explicitly run `meteor add react@0.1.14`?

**Comment by stubailo** [comment]
@ffxsam that's true!

**Comment by oles-io** [comment]
Would love to see this bumped to version 0.14, along with updated examples after :)

**Comment by ccorcos** [comment]
If you haven't check it out yet `webpack:webpack` is pretty amazing -- you may want to look into using it for React

**Comment by stubailo** [comment]
@ccorcos will that make this package better somehow if we switch to that over cosmos:browserify?

**Comment by ffxsam** [comment]
>If you haven't check it out yet webpack:webpack is pretty amazing -- you may want to look into using it for React

I just can't bring myself to do it. It feels very un-Meteor-like to me, like I'm taking away what's unique to Meteor (its package system) and throwing "old-fashioned" Node into the mix.

This is why I chose to go with `meteorflux:dispatcher` for my Flux architecture, as opposed to using Redux. No hackery with browserify, just add the package and boom, I have immediate access to `Dispatcher`.

I'm sure I sound a bit crazy.. :)

**Comment by ffxsam** [comment]
Oops - disregard that comment I deleted. I didn't realize what repo I was in. :D I understand React is wired into Meteor via browserify currently. So far it's been smooth sailing.

**Comment by ccorcos** [comment]
@stubailo its quite different from browserify because it basically takes over the entire build system. You'd require react and react-dom from NPM instead of this package and then you can use modules. 

The big win to me is HMR and the Redux/Redux Dev Tool. Check out this talk if you haven't -- it highlights features I just mentioned: https://www.youtube.com/watch?v=xsSnOQynTHs

And check out this demo app with meteor to get a feel for it: https://github.com/thereactivestack/kickstart-hugeapp

Some of other benefits are: Rebuild times are about 200ms and don't require a browser refresh, maintaining react component state. You can split up your app into [several entry points](https://webpack.github.io/docs/code-splitting.html) for quicker load times. And there's a plethora of amazing npm packages you can now user as well -- these are some of my favorite:
- https://www.npmjs.com/package/svg-react-loader
- https://www.npmjs.com/package/resize-image-loader ([presentation](http://puppybits.github.io/talks/More_Speed_More_Money.html#1))

**Comment by stubailo** [comment]
@ccorcos I understand the benefits of that package _overall_ for Meteor - it seems awesome! I was just asking specifically here. Since we probably aren't going to ask people to switch over to that build system to use this package, I'm guessing it won't help with this particular scenario.

**Comment by ccorcos** [comment]
Well you could use webpack only to process the react components and give you HMR. No configuration. 200ms rebuild. Maintains component state.

**Comment by stubailo** [comment]
Yes, I understand.

**Comment by ccorcos** [comment]
Have you tried HMR yet? Taste the cool aid!! :yum:

**Comment by stubailo** [comment]
I started a PR to update to 0.14.0.

**Comment by okada** [comment]
Any idea when React 0.14 integration will be available? I'm using React components that depend on the new version and will have to convert to the old (buggy) version but would prefer to wait if this will be available in the next few weeks.

**Comment by infowaybs** [comment]
+1

**Comment by stubailo** [comment]
I'm hoping to get this done in the next week or so - it would be a shame to lag longer than that.

**Comment by eXon** [comment]
I would rather have it rights than have it wrong fast. Keep up the good work :)

**Comment by stubailo** [comment]
Yeah it's pretty annoying since they split up React and ReactDOM, and renamed all of the submodules of React, and moved out the addons, which means it's not as trivial of a change as I would have hoped.

**Comment by okada** [comment]
This is a great. And thank you for the feedback.

**Comment by john-osullivan** [comment]
Thanks for being proactive on upgrading this!  I'm also using some react packages which are breaking because they depend on the new version.  Thumbs up for waiting a little longer to get it done right, I look forward to using the new version once it's ready to go.

**Comment by maartenbusstra** [comment]
@stubailo That's the downside of integrating stuff that's pre 1.0 :)

**Comment by Siyfion** [comment]
I'm in the same boat as @okada, having loads of React packages that seem to have abandoned support for 0.13.x almost the moment 0.14.x was announced. It'd definitely be good to get this done sooner rather than later.

**Comment by coostendorp** [comment]
+1

**Comment by nikhildaga** [comment]
+1

**Comment by qnub** [comment]
0.14.1 React released…

**Comment by stubailo** [comment]
0.14.0 released. Working on 0.14.1 now.

**Comment by ffxsam** [comment]
Awesome work, Sashko! I noticed the new version is 0.2.1. Any reason for the diversion in version numbering? How will we be able to tell what version of React this corresponds to?

Just a reminder to people using React: 0.14 introduces breaking changes:
https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html

**Comment by stubailo** [comment]
Yeah so I probably screwed up the versioning. I think I might republish it again just to sync up the number.

The "real" answer is that `react-runtime` is the one that corresponds to React's version number. But we should change `react` to do the same.

**Comment by ffxsam** [comment]
Ahh ok. Thanks :) Also, just a suggestion: you may want to pin 0.1.13 so people have to do a manual `meteor add` to upgrade, since there are breaking changes. But I dunno if that confuses people when they run `meteor update` and their packages seem stuck.

**Comment by stubailo** [comment]
I dunno, until further notice I'm just going to go with react's version numbers, rather than trying to convert their numbers into some sort of SemVer thing.

Anyway, `react` and co. 0.14.1 are out now.

**Comment by Siyfion** [comment]
Fantastic Sashko / @stubailo! Really, I think it's great that we're up-to-date with it all. :+1:

**Comment by marbemac** [comment]
@stubailo What's the recommended browserify.options file to expose ReactDOM to npm packages (like we expose React to them already)? I don't see a ReactDOM.require function available. This is what I'm doing right now - good or bad?

In any case, might be a good idea to update the meteor react docs with the recommended method.

```js
{
  "transforms": {
    "externalify": {
      "global": true,
      "external": {
        "react": "React.require",
        "react-dom": "ReactDOM.constructor"
      }
    }
  }
}
```

**Comment by marbemac** [comment]
That's actually not working correctly - no browserify compile errors, but packages (like ReactDND or ReactOnClickOutside) don't seem to have access to it.

**Comment by stubailo** [comment]
Can you file a separate issue for this?

**Comment by marbemac** [comment]
Done, thanks!

**Comment by v3rron** [comment]
Is this package now on React 0.14.0 or 0.14.2 ?

**Comment by stubailo** [comment]
0.14.1

**Comment by micabe** [comment]
DId you test the new version with Internet Explorer 8 ? it seems the compatibility is broken..

**Comment by micabe** [comment]
last version 0.14.4 in react-runtime seem s to fix it
