### ISSUE TITLE
blaze-as-react

### ISSUE THREAD

**Issue by TomFreudenberg** [meteor/react-packages#119]
Hi, would you like to add this package

https://github.com/4commerce-technologies-AG/meteor-package-blaze-as-react

as package to this repository?

I would be able to create a PR if this is something you like

Thanks for a short note
Tom

**Comment by stubailo** [comment]
Hey, I don't think we will add the code of the package to the repository right now, but I'd be happy to accept a PR listing it on this page: http://react-in-meteor.readthedocs.org/en/latest/community/

Once it gets more adoption in the community, we can add a page to the guide about it, like we have for React in Blaze.

**Comment by TomFreudenberg** [comment]
Ok, I will do so - thanks for feedback
