### ISSUE TITLE
How do we expose ReactDOM to npm packages via browserify?

### ISSUE THREAD

**Issue by marbemac** [meteor/react-packages#123]
What's the recommended browserify.options file to expose ReactDOM to npm packages (like we expose React to them already)? I don't see a ReactDOM.require function available. This is needed in many react packages including ReactDND and ReactOnClickOutside.

**Comment by marbemac** [comment]
Solved with exposify (instead of externalify):

```js
{
  "transforms": {
    "exposify": {
      "global": true,
      "expose": {
        "react": "React",
        "react-dom": "ReactDOM"
      }
    }
  }
}
```

Perhaps the meteor + react docs should be updated?

**Comment by stubailo** [comment]
Haha, we go through this loop every time `externalify` doesn't work.

`exposify` is great, and if it works for you, then that is awesome. However, other NPM packages you are using, for example `material-ui`, won't be able to import sub-modules of React, like so: `require('react/lib/invariant')`. This is what `externalify` does - it makes sure that all sub-modules are accessible.

So perhaps, `exposify` is a good workaround for now; I will look at how to make things work with `externalify` as soon as I can.

**Comment by marbemac** [comment]
Ah ok, I didn't know that! Exposify works for me for now, will move back to externalify when it works :). Thanks.

**Comment by marbemac** [comment]
Following up, I'm using React.renderToString, which has been moved into ReactDOMServer.renderToString = require('react-dom/server'). Any chance at exposing ReactDOMServer as well as ReactDOM? Happy to create a separate issue if appropriate.

**Comment by otroboe** [comment]
Any news about this ?

App is still working but I have this warning:
```
Warning: React.render is deprecated. Please use ReactDOM.render from require('react-dom') instead.
```

Document and tutorial are not up to date :s

**Comment by mayacode** [comment]
+1

**Comment by DClark5218** [comment]
+1

**Comment by Firfi** [comment]
+1

**Comment by Un3qual** [comment]
+1

**Comment by Un3qual** [comment]
+1

**Comment by payner35** [comment]
+1

**Comment by yyx990803** [comment]
You can get it working by configuring externalify like this:

``` json
{
  "transforms": {
    "externalify": {
      "global": true,
      "external": {
        "react": "React.require",
        "react-dom": "React.require"
      }
    }
  }
}
```

Basically, tell all npm packages that requires `react` or `react-dom` to use the global `React.require()` instead of direct `require()`.

**Comment by bcbrian** [comment]
Not entirely sure on this but would cause my unit tests to break? For example, I have a submit function that gets values from an input via:
``` ReactDOM.findDOMNode(this.refs.name).value.trim(); ```
It works just fine when I am using the page but when the tinytest hits this line it blows up and says
```ReactDOM is not defined```
If I change it back to the depricated ```React``` it works just fine. Just curious if these are related.

**Comment by tmeasday** [comment]
This will no longer be an issue in 1.3
