### ISSUE TITLE
react-todos outdated?

### ISSUE THREAD

**Issue by trsh** [meteor/react-packages#125]
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).

Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).

Uncaught TypeError: ReactRouter.create is not a function(anonymous function) @ routes.jsx:17(anonymous function) @ routes.jsx?b2c75699d19f4d9965c84c2deb0070d79789c033:36

**Comment by stubailo** [comment]
Ah, crap - I accepted a PR that changed a bunch of stuff while upgrading to React 0.14, and I guess the app broke. Thoughts about how we could fix it? I guess there's a totally new version of React Router now, so we probably need to change the syntax

**Comment by trsh** [comment]
stubailo I'm a new to meteor and react. I finished the official tutorial from meteor page and headed over here, as this more advanced with routing etc. Sadly it's broken :)

**Comment by eXon** [comment]
Why not update the example by using the `reactrouter:react-router` example instead. It is already on the last official version

**Comment by stubailo** [comment]
> using the reactrouter:react-router example

I went to the repo for that package and I can't find the example app. Where would it be? Or are you talking about the code snippet?

**Comment by eXon** [comment]
There is no code example outside the readme. I can update the todo-example and do a PR and you could choose then if you think it is a good idea or not. It is pretty easy to do.

**Comment by stubailo** [comment]
That would be awesome! I'm OK with using the react router package, if it's the newest version.

**Comment by bwhitty** [comment]
Agree with using  the `reactrouter-react-router` package. Been using it in production for a while, works great. Removes the need for the npm container.

**Comment by trsh** [comment]
eXon GO GO! :) . Let me know when it's done, I will close this issue than.

**Comment by stubailo** [comment]
It's done!

**Comment by trsh** [comment]
Well done! Thanks!
