### ISSUE TITLE
Returning undefined from getMeteorData throws confusing error

### ISSUE THREAD

**Issue by rdickert** [meteor/react-packages#129]
Given an empty collection called `Things`, using this in a component

```
  getMeteorData() {
    return Things.findOne();
  },
```

will break the app with a hard-to-trace error ("Uncaught TypeError: Cannot convert undefined or null to object" in `es5-shim`). 

If you instead return `Things.find().fetch()`, it works. I found that trying to return a string from `getMeteorData` returns a much more helpful error with a stack trace ("Expected object returned from getMeteorData"). I think it more reasonable for the mixin to treat `undefined` as an empty object (by analogy to how data works in Blaze), but if not, it should at least throw the helpful error.

**Comment by stubailo** [comment]
Interesting. I think the intention is that it should be used like:

```
getMeteorData() {
  return {
    thing: Things.findOne()
  }
}
```

Then it is much more clear when you reference it by `this.data.thing.x` rather than just `this.data.x`. Plus, it will be easier to add more data later.

However, we should still have some checks here for undefined, null, strings, etc.

**Comment by rdickert** [comment]
I think both patterns are reasonable. Your point about adding data later is well taken, but there might be a place for a react object that is just a view of a db object (a bit like using `transform` on the collection) and should never have other data elements tied to it. `this.data.thing.x` feels verbose in a component called `Thing`. Either way, as long as the mixin throws a useful error ("please return an object!"), people can decide for themselves.

**Comment by MHerszak** [comment]
I am getting this error: 'Uncaught Error: Expected object returned from getMeteorData'. When I comment it out everything is fine. It seems a bit odd to me. Any idea how to solve this?

```javascript
    mixins: [ReactMeteorData],

    getMeteorData()
    {
        return {
            loggingIn: false,
        };
    },
```

**Comment by rantav** [comment]
Here's a similar issue (perhaps the same issue).

With the following code: 

```
  getMeteorData() {
    let user = Meteor.user();
    if (user) {
      ... calculate more about the user
      return {
        currentUser: user,
        ... return more about this user
      };
    }
  }
```

This thing runs well in development mode but fails in production mode (`--production`). 
When getMeteorData returns undefined - works perfectly well while developing but throws difficult to trace error when packaged for production. Not sure why the diff, but evidently there is. 

The error in production goes something like this: 

```
Uncaught TypeError: Cannot convert undefined or null to objecta @ 2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:134
n.componentWillMount @ 2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:134
E.mountComponent @ 2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:120
i.mountComponent @ 2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:122
y.Mixin.mountChildren @ 2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:122
E.Mixin._createContentMarkup @ 2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:120
E.Mixin.mountComponent @ 2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:120
i.mountComponent @ 2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:122
E.mountComponent @ 2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:120
i.mountComponent @ 2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:122
E.mountComponent @ 2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:120
i.mountComponent @ 2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:122
m @ 2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:122
o.perform @ 2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:124
v @ 2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:122
o.perform @ 2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:124
d.batchedUpdates @ 2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:121
i @ 2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:123
ee._renderNewRootComponent @ 2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:122
ee._renderSubtreeIntoContainer @ 2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:122
ee.render @ 2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:122
(anonymous function) @ 2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:136
(anonymous function) @ 2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:136
(anonymous function) @ 2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:136

2ecdff8022a6dbbd7d29b67c1d3b0e17ce845bd2.js?meteor_js_resource=true:3 
Exception from Tracker recompute function:
```


A workaround is simple, just don't return `undefined`, but that's a gotcha b/c it is only revealed in prod: 

```
  getMeteorData() {
    let user = Meteor.user();
    if (user) {
      ... calculate more about the user
      return {
        currentUser: user,
        ... return more about this user
      };
    } else {
      return {};
    }
  }
```

**Comment by filipenevola** [comment]
I'm closing this just because it's too old. We can open new issues for items that are still valid.
