### ISSUE TITLE
Official react package

### ISSUE THREAD

**Issue by dropfen** [meteor/react-packages#13]
Hello, 
I just wanted to ask, why the official react package is not in listed here. I guess I missed some discussion about it. So please could some one point me to the right answer?

**Comment by rclai** [comment]
Look [here](https://github.com/meteor/react-packages/blob/master/react/package.js).

**Comment by dropfen** [comment]
@rclai 
Thx, I guess I got it! :)

**Comment by dropfen** [comment]
The set of is really clear and easy to understand, great work!

**Comment by AdamBrodzinski** [comment]
@dropfen  Also the 'official'  `reactjs:js` package adds in extra things like mixins that overlap with what MDG is making. The MDG react will ultimately use the regular React runtime js file and then add their own sub packages to enhance the whole thing for Meteor.

**Comment by dropfen** [comment]
Oh yes the thing with their own ReactMeteor was a bit weird, so this Set of packages is more understandable and the skeleton for creating own react packages is really awesome. We can just take it to convert already existing react components to meteor packages.. Really cool :)
