### ISSUE TITLE
material-ui outdated

### ISSUE THREAD

**Issue by markoshust** [meteor/react-packages#130]
I tried to use the material-ui example, but its very outdated and didn't work. I created a new package: https://atmospherejs.com/markoshust/material-ui

**Comment by stubailo** [comment]
I'd love to have a PR to update it to use a package for material UI.

**Comment by markoshust** [comment]
Sure, give me a few days and I'll have one over to you

**Comment by stubailo** [comment]
Thanks!

**Comment by markoshust** [comment]
All set... https://github.com/meteor/react-packages/pull/134
