### ISSUE TITLE
PureRenderMixin is undefined

### ISSUE THREAD

**Issue by j20** [meteor/react-packages#133]
Attempting to use `mixins: [PureRenderMixin],` within any component causes a console warning of `ReferenceError: PureRenderMixin is not defined` and breaks the app causing an empty white screen. When this happens another console warning follows: `ReferenceError: FooBarComponent is not defined` for the component that attempted to use the pure render mixin.

Removing `mixins: [PureRenderMixin],` from the component causes the app to function correctly again.

I've tested using pure render in various components with the same result. I've tested components that use props, no state, no meteor data and also in components that use no props, no state, & no meteor data.

Fully up to date meteor installation with latest packages.

**Comment by VladShcherbin** [comment]
@j20 you need to define it first:

```js
PureRenderMixin = React.addons.PureRenderMixin;
```

Then you can use it everywhere in your app.

**Comment by j20** [comment]
Thank you @VladShcherbin
