### ISSUE TITLE
React.DOM split from React core in v14

### ISSUE THREAD

**Issue by genyded** [meteor/react-packages#135]
React split out React.DOM from the core in [v14](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#two-packages-react-and-react-dom)... are there plans to add a  react-DOM package to Meteor? Some third party packages such as [Material-UI](https://github.com/callemall/material-ui) depend on this and will return `npm WARN EPEERINVALID material-ui@0.13.2 requires a peer of react-dom@^0.14.0 but
t none was installed` when using the latest Meteor.

I am going to try to pull it in via NPM for now, but that could get hard to manage across release and it also seems it would be better to be consistent.

**Comment by Un3qual** [comment]
+1

**Comment by yyx990803** [comment]
This is now available globally as `ReactDOM`.
