### ISSUE TITLE
React Template Helper: Passing in a React Class as prop

### ISSUE THREAD

**Issue by owenhoskins** [meteor/react-packages#138]
Hello, I've just start experimenting with this set of packages and the prospects are pretty exciting.

I have a simple use case where I am trying to determine if React Template Helper is designed to handle.

Take this package for example: [React Modal](https://atmospherejs.com/patrickml/react-modal)

According to it's documentation, you pass in other React Classes to the render function within a JSX file, like so:
`<Modal title="React Modal" content={ < SomeContent /> } id="modal-1"/>`

I was exploring if the same could be achieved with the Template Helper:

JSX

```
Modal = React.createClass({
  render () {
    return (
      <div className="md-modal md-effect-1" id={this.props.id}>
        <div className="md-content">
          <h3>{this.props.title}</h3>
          <div className="md-body">
            {this.props.content}
            <i className="md-close close ion ion-close"></i>
          </div>
        </div>
      </div>
    )
  }
});

SampleContent = React.createClass({
  render () {
    return (
      <h2>Hello I am test content!</h2>
    )
  }
});
```

Template

```
<template name="modalTest">
  <div>{{> React component=Modal title='React Modal' content=SomeContent id='modal-1'}}</div>
</template>
```

JS

```
Template.modalTest.helpers({
  Modal() {
    return Modal;
  },
  SomeContent() {
    return SomeContent;
  }
})
```

Inspecting the Modal class with the Chrome React Debugger shows that SomeContent is passed in as a function not as a React Class.

Recreating this test sans Meteor and using the `content={ <SomeContent />}` syntax the Class is passed in as expected.

Could this is due to running the Class through the template helper function. Might there another way that one could approach this??

Update:

I took a stab at passing the SampleContent function as a child to createElement in react-template-helper.js

`ReactDOM.render(React.createElement(comp, props, children), container);`

but the result is the same: the React Classes-ness gets lost and a function is added to the props.

In the Template.React.onRendered there is no difference between "comp" and "children", both are functions extending the React Class prototype. 

I wonder what is happening inside React.createElement...

Any thoughts on this would be appreciated! Thanks!

best,
Owen

**Comment by owenhoskins** [comment]
Follow up. I did a little song and dance with React to find a work-around.

`````
function Wrapped(Component) {
    return React.createClass({
        render: function() {
            return ( 
                <div className="wrapper"> 
                    <Component {...this.props}/>
                </div>
            );
        }    
    });
};

var Hello = React.createClass({
    render: function() {
        return ( 
           <div> 
               Hello {this.props.name}                    
           </div>
        );
    }
});

var WrappedHello = Wrapped(Hello);

Template.hello.helpers({
  WrappedHello() {
    return WrappedHello;
  }
})

<template name="hello">
  <div>{{> WrappedHello name="Owen"}}</div>
</template>
`````
Still, I think it would be cool to directly include children React Classes via the Template helper. Curious to hear any thoughts on this. Thanks!

best,
O

**Comment by filipenevola** [comment]
I'm closing this just because it's too old. We can open new issues for items that are still valid.
