### ISSUE TITLE
Question: why do you have React installed with Meteor package, but React libraries with npm+browserify? 

### ISSUE THREAD

**Issue by Firfi** [meteor/react-packages#139]
Hey, 

wouldn't it be cleaner way to install everything (React and ReactDOM + packages) through npm?

Thanks,
Igor

**Comment by yyx990803** [comment]
It indeed is! The current implementation has to deal with a number of limitations in Meteor's current package system to ensure things work together, and we definitely hope to improve it in the future. With ES6 modules planned in 1.3, we should also be able to provide a much smoother npm integration, which would in turn make working with React and React libraries a lot easier.

**Comment by john-osullivan** [comment]
I'm running into a few nasty bugs getting Meteor's React to play nice with community-made NPM libraries.  How do I expose Meteor's built-in React and ReactDOM to those packages?

**Comment by yyx990803** [comment]
@john-osullivan see https://github.com/meteor/react-packages/issues/123#issuecomment-163097683
