### ISSUE TITLE
<audio> on iOS fails when passing reactive data

### ISSUE THREAD

**Issue by ffxsam** [meteor/react-packages#142]
This is quite strange! I noticed my audio player was not working on iOS, but in every desktop browser it was fine. Took a _really_ long time to figure this out, but it boils down to passing a variable returned from `getMeteorData` into my component. Apparently on iOS, it doesn't see this as a user-generated play command, so it ignores it. It's easier to demonstrate it, so here's the repo:

https://github.com/ffxsam/meteor-react-ios-bug

The way to fix this is to edit `Home.jsx` and change the `AudioPlayer` line to:

```
<AudioPlayer audioPlayerData={this.state.audioPlayerData} />
```

And modify `doit` so that it sets state instead of the reactive var.

[This StackOverflow answer](http://stackoverflow.com/questions/8179585/playing-audio-on-ipad) illustrates the problem.

Strange that a state change works ok, but reactive var change fails.

**Comment by filipenevola** [comment]
I'm closing this just because it's too old. We can open new issues for items that are still valid.
