### ISSUE TITLE
Update React to latest v0.14.3

### ISSUE THREAD

**Issue by praneybehl** [meteor/react-packages#143]
Would like to request the react packages to be updated to the latest v0.14.3 since a lot of react-components have moved to the latest version and do not support later versions.

**Comment by ncphillips** [comment]
+1

**Comment by Un3qual** [comment]
+1

**Comment by ffxsam** [comment]
+1. In IE10 and IE11, onClick handlers are 100% broken in 0.14.1. Not good :)

**Comment by Jpunt** [comment]
Same here. Is there a way to do this ourselves?

**Comment by stubailo** [comment]
You could file a PR. Basically just cmd-f for everywhere the number 0.14.1 appears, and make sure everything still works.

**Comment by Jpunt** [comment]
Done: https://github.com/meteor/react-packages/pull/146

**Comment by yyx990803** [comment]
Just published react@0.14.3!
