### ISSUE TITLE
1.3 beta and jsx

### ISSUE THREAD

**Issue by kzvaigzne** [meteor/react-packages#148]
With current version import/export syntax isn't working with the Meter 1.3 beta

`Uncaught SyntaxError: Unexpected token import` same for export

**Comment by avital** [comment]
Did you add the `modules` package? Can you supply a repro in the form of a Meteor app in a Git repository we can clone and run?

**Comment by kzvaigzne** [comment]
You can clone https://github.com/kzvaigzne/jsx-test and run it, it will provide the `Uncaught SyntaxError: Unexpected token export` error in browser console as reported.

The `import` error can be seen if you rename `client/main.js` to `client/main.jsx`

The `modules` package comes baseline with every new app created in 1.3(what I did for the test repo) but adding it manually still gives the same error.

**Comment by avital** [comment]
Thanks, we're tracking this in https://github.com/meteor/meteor/issues/5827
