### ISSUE TITLE
Tinytest says ReactDOM is not defined

### ISSUE THREAD

**Issue by bcbrian** [meteor/react-packages#150]
I have a submit function that gets values from an input via:

```
ReactDOM.findDOMNode(this.refs.name).value.trim();
```

It works just fine when I am using the page but when the tinytest hits this line it blows up and says

```
ReactDOM is not defined
```

If I change it back to the deprecated 

```
React
```

it works just fine, except now the app displays the deprecating error for

```
React.findDOMNode
```

**Comment by vicusbass** [comment]
Same (or bigger) problem when using dpraburaj:react-spin package. Which depends on ReactDOM object

**Comment by filipenevola** [comment]
I'm closing this just because it's too old. We can open new issues for items that are still valid.
