### ISSUE TITLE
app.browserify.options.json throws syntax error

### ISSUE THREAD

**Issue by quackware** [meteor/react-packages#153]
Hello!

The `app.browserify.options.json` on http://react-in-meteor.readthedocs.org/en/latest/client-npm/ throws a syntax error if you copy it directly from the page

    {
      "transforms": {
        "externalify": {
          "global": true,
          "external": {
            "react": "React.require",
            // not necessary for react-router, but may be
            // needed for other libraries that requires react-dom
            "react-dom": "React.require"
          }
        }
      }
    }

Produces:

    => Errors prevented startup:                  
       
       While processing files with cosmos:browserify (for target web.browser):
       lib/app.browserify.js: Unexpected token /
       
       While processing files with cosmos:browserify (for target os.osx.x86_64):
       lib/app.browserify.js: Unexpected token /

Ideally you would want to remove the comments in the json file in order for the example to work. This may be obvious for those familiar with json but can catch beginners off guard (especially since the error message is not that useful).

**Comment by stubailo** [comment]
Thanks for the fix!

**Comment by SachaG** [comment]
Just got bitten by this. I'd suggest reopening the issue since the sample code still includes the comments?
