### ISSUE TITLE
Subcollections don't trigger updates ?

### ISSUE THREAD

**Issue by dperetti** [meteor/react-packages#160]
I have a Commands collection. Each command has lines.

With Blaze, I would just use `commands = commands.find({})` and `{{#each commands}} Command ...{{#each lines}} Line...{{/each}}{{/each}}` to display them.

When new lines are added to a command (using `$push`), lines are updated as expected.

Using React and `getMeteorData()` my commands are displayed correctly, but subsequent line updates don't trigger updates.

It's not a React issue as I'm pretty comfortable with it.

Any thought ?

**Comment by filipenevola** [comment]
I'm closing this just because it's too old. We can open new issues for items that are still valid.
