### ISSUE TITLE
0.14.4 problem with Mup: 'no such file or directory, ... .../node_modules/esprima-fb/.#README.md'

### ISSUE THREAD

**Issue by Batistleman** [meteor/react-packages#165]
There might be a problem with version 0.14.4

Related discussion here: https://forums.meteor.com/t/mupx-archiving-failed-enoent/15281
and here: https://github.com/arunoda/meteor-up/issues/812

**Comment by tmeasday** [comment]
Any idea what the problem is?

**Comment by filipenevola** [comment]
I'm closing this just because it's too old. We can open new issues for items that are still valid.
