### ISSUE TITLE
Cursor warning in `getMeteorData()` should be disable-able and not appear on production.

### ISSUE THREAD

**Issue by tmeasday** [meteor/react-packages#166]
In certain cases it make sense to e.g. pass a cursor in as a prop of a subcomponent (specifically if you want to observe it).

You should be able to suppress the error in this case.

Also it logs this error on production which is unusual for these kind of errors

https://github.com/meteor/meteor/issues/5282

**Comment by filipenevola** [comment]
I'm closing this just because it's too old. We can open new issues for items that are still valid.
