### ISSUE TITLE
App does not render when ReactMeteorData mixin is present

### ISSUE THREAD

**Issue by guivho** [meteor/react-packages#167]
I posted on stackoverflow about a strange problem.
[App does not render when ReactMeteorData mixin is present](http://stackoverflow.com/questions/34882078/app-does-not-render-when-reactmeteordata-mixin-is-present)
Please advise

**Comment by stubailo** [comment]
Hi, StackOverflow and the Meteor forum are the best places to ask for questions. Please post there instead.

https://forums.meteor.com/c/help
