### ISSUE TITLE
reactContainer - Can we use it yet?

### ISSUE THREAD

**Issue by ciwolsey** [meteor/react-packages#174]
@benjamn Is there a way to use createContainer yet? It's documentated here: http://guide.meteor.com/v1.3/react.html#using-createContainer but when I import I get the old mixin.

**Comment by vadimmelnicuk** [comment]
Curious as well. I tried today, but createContainer didn't work.

**Comment by tmeasday** [comment]
Try `meteor add react-meteor-data@0.2.6-beta.16`

**Comment by ciwolsey** [comment]
Also unless they updated the docs as per my PR you need to:
```
import { reactContainer }
```
rather than:
```
import reactContainer
```

**Comment by tmeasday** [comment]
@ciwolsey where was that wrong? I think we merged it but let me know if not!

**Comment by ciwolsey** [comment]
@tmeasyday you're right it's merged :)

**Comment by ciwolsey** [comment]
Anyway, this issue is resolved for me so I'll close it off. Hope that's ok.
