### ISSUE TITLE
Meteor.user() is undefined after reload the page ?

### ISSUE THREAD

**Issue by hojas** [meteor/react-packages#176]
```js
var HelloUser = React.createClass({
    mixins: [ReactMeteorData],
    getMeteorData() {
        return {
             currentUser: Meteor.user()
        };
    },
    render() {
        return <span>Hello {this.data.currentUser.username}!</span>;
    }
});
```

I got `TypeError: Meteor.user() is undefined` after I reload the page.Dose this an issue ?

**Comment by stubailo** [comment]
It's hard to understand what the issue is here without a reproduction we can run.

**Comment by hojas** [comment]
The user is logined. But, Meteor.user() will be null after reload the page.

**Comment by stubailo** [comment]
Yes. That doesn't help me understand the issue, because there could be many possible causes. I'll reopen if there is a reproduction following these directions: https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor

**Comment by tarun-batra** [comment]
I recently faced similar issue.
What actually happens is, that on a hot reload, Meteor.user() returns undefined because of the subscription maybe (due to which Roles package failed and the access was not granted in my case).
As expected, putting the code in Tracker works fun.

**Comment by kkent030315** [comment]
Hi 8 years past.

This is an ordinal cuncurrency issue around the subscription (particularly to ``userData``). I encountered the same, and eventually figured out that the `Meteor.subscribe` and `root.render` are causing the issue.

Given that, you will need to guarantee the control flow of your code by leveraging on ready callback of `Meteor.subscribe` as follows:

```tsx
// Meteor 3.0.2

Meteor.startup(() => {
  const container = document.getElementById('root');
  const root = createRoot(container!);

  Meteor.subscribe('userData', () => {
    root.render(
      <React.StrictMode>
        <RouterProvider router={router} />
      </React.StrictMode>
    );
  });
});
```

Although this issue is eight years old and the framework had changed a lot, I presume this is some kind of a mix of different problem and regression..

**Comment by nachocodoner** [comment]
This can also be addressed in React by using useTracker on the Meteor.user() reactive data source, ensuring the computation re-runs when the user data becomes available, this is like waiting to onReady, except you can still provide any feedback to the user.

However, I'm not entirely sure if this targets the actual issue discussed here, as the problem's exact nature is still unclear to me.
