### ISSUE TITLE
Not compatible with React v15

### ISSUE THREAD

**Issue by ffxsam** [meteor/react-packages#183]
React 15.0.0 is out now! Unfortunately, Meteor's React packages don't work. I get warnings:

```
WARNING: npm peer requirements not installed:
 - react@15.0.0 installed, react@0.14.x needed
 - react-addons-pure-render-mixin@15.0.0 installed, react-addons-pure-render-mixin@0.14.x needed

Read more about installing npm peer dependencies:
  http://guide.meteor.com/using-packages.html#peer-npm-dependencies
```

But even though it's just a warning, my app ceases to work properly.

**Comment by ffxsam** [comment]
Update: app not working was my own fault. ;)

**Comment by codyparker** [comment]
What was it? I'm getting the same error.

**Comment by ffxsam** [comment]
It's just a warning, and it's because `react-meteor-data` is depending on React v0.14. The team is working on it.

**Comment by codyparker** [comment]
Right, OK thanks!

**Comment by stubailo** [comment]
I believe this is fixed now, if you update to the newest versions.
