### ISSUE TITLE
Ref property is not passed into Wrapped component

### ISSUE THREAD

**Issue by gerwinbrunner** [meteor/react-packages#189]
I have a container with a ref.
<AtInputContainer   ref="wrapper" field={this.props.field} />

But this ref is not passed to the Wrapped component. Any idea on how to do this?

export default AtInputContainer = createContainer(props => {
  console.log("AtTextInput", props);
  return {
    showLabels:      AccountsTemplates.options.showLabels,
  }
}, AtInput);

**Comment by filipenevola** [comment]
I'm closing this just because it's too old. We can open new issues for items that are still valid.
