### ISSUE TITLE
provide version number in package.json

### ISSUE THREAD

**Issue by jedwards1211** [meteor/react-packages#191]
this will enable us to `npm install git@github.com:meteor/react-packages`

**Comment by abernix** [comment]
These are not npm packages, but rather Meteor packages so the presence of a `package.json` in the root of this repository (or even the individual packages within this repo's `packages/` directory) won't have the effect you're expecting from `npm install`.  Please see https://github.com/meteor/react-packages/issues/221 for a general update on this repo.  `react` should be installed directly from `npm` and the `react-meteor-data` package can still be installed from `meteor add meteor:react-meteor-data`.
