### ISSUE TITLE
Document how to not use PureRenderMixin for createContainer

### ISSUE THREAD

**Issue by johnslemmer** [meteor/react-packages#193]
Pure render [doc](https://facebook.github.io/react/docs/pure-render-mixin.html) has a large note at the bottom that says:

> Furthermore, shouldComponentUpdate skips updates for the whole component subtree. Make sure all the children components are also "pure".

People are using createContainer in lots of places and it isn't even clearly documented that you can change the options to not use pure.  For instance using pure [prevents context changes](https://facebook.github.io/react/docs/context.html#known-limitations) from filtering down to children if the props or state didn't change that is being passed to createContainer.

For anyone looking for how to do this here is an example of how you can stop using pure when calling createContainer:

```
import { Meteor } from 'meteor/meteor';
import { createContainer } from 'meteor/react-meteor-data';
import MyPage from '/imports/ui/layouts/MyPage.jsx';

export default createContainer({
  getMeteorData: () => (
    {
      isLoggedIn: !!Meteor.userId(),
    }
  ),
  pure: false,
}, MyPage);

```

To be honest this just feels a bit clunky.  I think I would rather have a createContainer call that looks something like this with an extra options param at the end:

```
export default createContainer(() => (
    {
      isLoggedIn: !!Meteor.userId(),
    }
), MyPage, { pure: false });
```

**Comment by johnslemmer** [comment]
OK.  It looks like a [change](https://github.com/facebook/react/pull/6661) is coming from React real soon that will actually do some shallow comparison of context in pure components.  Can't wait.

This will make this issue less necessary.  But it would still be nice to offer this doc for people working with some odd deep nested properties or context.

**Comment by menelike** [comment]
Exactly my issue after debugging for an hour. The suggested solution seems absolutely valid.

**Comment by filipenevola** [comment]
I'm closing this just because it's too old. We can open new issues for items that are still valid.
