### ISSUE TITLE
missing `component` argument.

### ISSUE THREAD

**Issue by nialexsan** [meteor/react-packages#198]
The error occurs on using react components in blaze template.

main.html
`
<body>
  <h1>Welcome to Meteor!</h1>
  <div>{{> React component=ReactComponent}}</div>
</body>
`

main.js

`import { Template } from 'meteor/templating';`

`import React from 'react';`

`var ReactComponent = React.createClass({`
`render() {`
`return (`
`<h1>ReactComponent</h1>`
`);`
`}}`
`);`

`Template.hello.helpers({`
`ReactComponent () {`
`return ReactComponent;`
`}`
`});`

Error

> Error: In template "<body>", call to `{{> React ... }}` missing `component` argument.
>     at .<anonymous> (react-template-helper.js:23)
>     at view.js:199
>     at Function.Template._withTemplateInstanceFunc (template.js:465)
>     at view.js:197
>     at Object.Blaze._withCurrentView (view.js:538)
>     at viewAutorun (view.js:196)
>     at Tracker.Computation._compute (tracker.js:311)
>     at new Tracker.Computation (tracker.js:201)
>     at Object.Tracker.autorun (tracker.js:576)
>     at Blaze.View.autorun (view.js:209)

**Comment by aadamsx** [comment]
I'm getting the same error.  Did you make any progress on this?

**Comment by rwatts3** [comment]
Also receiving the same error.
Is there a solution ?

**Comment by aadamsx** [comment]
If you're on 1.3.* get to 1.4.1

**Comment by rwatts3** [comment]
Using 1.4.1.1
Basic meteor create project nothing extra

**Comment by aadamsx** [comment]
Show your code.

**Comment by rwatts3** [comment]
main.html
```html
<head>
  <title>sandbox</title>
</head>

<body>
  <h1>Welcome to Meteor!</h1>

  {{> hello}}
  {{> info}}
  
</body>

<template name="hello">
  <button>Click Me</button>
  <p>You've pressed the button {{counter}} times.</p>
</template>

<template name="info">
  <h2>Learn Meteor!</h2>
  <ul>
    <li><a href="https://www.meteor.com/try" target="_blank">Do the Tutorial</a></li>
    <li><a href="http://guide.meteor.com" target="_blank">Follow the Guide</a></li>
    <li><a href="https://docs.meteor.com" target="_blank">Read the Docs</a></li>
    <li><a href="https://forums.meteor.com" target="_blank">Discussions</a></li>
  </ul>
  	<div>
		{{> React component=Test}}
	</div>
</template>

```

main.js
```js
import { Template } from 'meteor/templating';
import { ReactiveVar } from 'meteor/reactive-var';


import './main.html';
import { Test } from '/imports/components/Test.jsx';

Template.hello.onCreated(function helloOnCreated() {
  // counter starts at 0
  this.counter = new ReactiveVar(0);
});

Template.hello.helpers({
  counter() {
    return Template.instance().counter.get();
  },
});

Template.hello.events({
  'click button'(event, instance) {
    // increment the counter when button is clicked
    instance.counter.set(instance.counter.get() + 1);
  },
});


Template.info.helpers({
	Test() {
		return Test;
	}
});
```

component

```js
// import SnackBar from 'essence-snackbar';
import React from 'react';

export default class Test extends React.Component {
	render() {
		<div>
			<p> Hello World</p>
		</div>
	}
};
```

**Comment by aadamsx** [comment]
change this:

```javascript
import { Test } from '/imports/components/Test.jsx';
```

to work like command line.  For example if you are two levels down from the import dir:

```javascript
import { Test } from '../../imports/components/Test.jsx';
```

**Comment by rwatts3** [comment]
Made the change and have the same issue. 
The problem wasn't with the component being loaded, it's imported properly. 
The problem appears to be elsewhere .

Hopefully that helps.

**Comment by pandabrand** [comment]
Was there ever a resolution on this? I am currently getting this as well. Worked as a stateless component, then broke when I changed to a stateful component. Now neither stateful or stateless works.

**Comment by vladbalan** [comment]
+1

**Comment by nemaniarjun** [comment]
Still happening :(

**Comment by ramsaymax** [comment]
I'm having this issue also... did any of you find a resolution?

**Comment by rjakobsson** [comment]
I'm getting the same error message, on Meter 1.4.2.3.

**Comment by derwaldgeist** [comment]
+1 Same problem here on 1.5.0

@rjakobsson: what do you mean by "load order issue"?

**Comment by derwaldgeist** [comment]
Update: The error was on my side. The helper looked like this:

```js
HomeComponent: () => HomeContainer
```

instead of

```js
HomeContainer: () => HomeContainer
```

The error message is a bit misleading in these cases.

**Comment by c316** [comment]
My problem ended up being that I was trying to import the wrong .html file (had the wrong name). Although I had stop meteor from running and then start it again before the error message would change.

**Comment by derwaldgeist** [comment]
Glad to see I'm not the only one using this package...

**Comment by filipenevola** [comment]
I'm closing this just because it's too old. We can open new issues for items that are still valid.

Most of these items were solved already or replaced by new strategies (like hooks)
