### ISSUE TITLE
Remove "react-addons-pure-render-mixin"?

### ISSUE THREAD

**Issue by MHerszak** [meteor/react-packages#200]
I have a question. In regards to this post, [https://facebook.github.io/react/blog/2016/07/13/mixins-considered-harmful.html#solution](https://facebook.github.io/react/blog/2016/07/13/mixins-considered-harmful.html#solution) would it be possible to remove "react-addons-pure-render-mixin" from "react-meteor-data"? They suggest to start using `var shallowCompare = require('react-addons-shallow-compare');` for `shouldComponentUpdate` I am not sure if this is possible or not? Thanks

**Comment by MHerszak** [comment]
Nvm. I just checked `shallowCompare` and it has a dependency to lodash `lodash.keys`. It would make sense to for us to apply underscore to mimic shallowCompare.

**Comment by MentalGear** [comment]
I think now the recommend the use of PureComponent in the react guide.
