### ISSUE TITLE
createContainer that allows creating ReactiveVar in its scope

### ISSUE THREAD

**Issue by raaymax** [meteor/react-packages#203]
It would be nice to have ability to create ReactiveVar somewhere in scope of container. Creating wrapper object for wrapper object just for variable declaration is a little redundant.
Here is example usage:

``` js
export default createContainer({
    getInitialMeteorData(){
        return {
            selection: new ReactiveVar(null)
        };
    },
    getMeteorData(props, initial){
        var imageId = initial.selection.get();
        var avatar = null;
        if(avatarId) {
            avatar = Files.findOne({_id: imageId});
        }
        return {
            selection: initial.selection,
            avatar: avatar,
        };
    }
}, UserForm);
```

What do you think?

**Comment by ecwyne** [comment]
@raaymax how are you able to achieve this currently? I'm running into this exact situation.

**Comment by mokolodi1** [comment]
See #213!

@raaymax I've opted to use the React-compatible name `getInitialState` and then I pass that state into `getMeteorData` as an argument as well as via `this.state`.

**Comment by filipenevola** [comment]
I'm closing this just because it's too old. We can open new issues for items that are still valid.

Most of these items were solved already or replaced by new strategies (like hooks)
