### ISSUE TITLE
container displayName doesn't work as a key in lists

### ISSUE THREAD

**Issue by raffomania** [meteor/react-packages#208]
I have a reactCSSTransitionGroup to enable transitions between pages in my app. I use the `displayName` of page components as the `key` prop. When using `createContainer` to wrap my page components, the `displayName` is always `MeteorDataContainer`, breaking transitions.

Would it be appropriate to incorporate the child component name in the `displayName`, something like `MeteorDataContainer-{child}`?

**Comment by filipenevola** [comment]
I'm closing this just because it's too old. We can open new issues for items that are still valid.

Most of these items were solved already or replaced by new strategies (like hooks)
