### ISSUE TITLE
react-meteor-data & React 16 - Publications Unsubscribing

### ISSUE THREAD

**Issue by stolinski** [meteor/react-packages#214]
Subscriptions in React 16 subscribe correctly, but unsubscribe moments later.

Also

I'm getting `npm peer requirements (for react-meteor-data) not installed: - react@16.0.0-alpha.4 installed, react@15.x needed` after upgrading to React 16.

**Comment by stolinski** [comment]
This probably isn't important until 16 is fully released.

**Comment by purplecones** [comment]
More relevant now that React 16 has been released. I'm running into same warning.

**Comment by klaussner** [comment]
@stolinski Are you sure that the subscription issue is related to React 16? I tried to reproduce it (with the final release, not the alpha version) but subscriptions worked as expected in the function passed to `createContainer`/`withTracker`.

**Comment by stolinski** [comment]
@klaussner I've been meaning to edit this issue. I stopped having these subscription issues on later React 16 RCs. Just the console warning now.

**Comment by tafelito** [comment]
Is this published yet? I tried to update to 0.2.14 but I get this error when I manually updated it

```
=> Errors prevented startup:

   While selecting package versions:
   error: Potentially incompatible change required to top-level dependency:
   react-meteor-data 0.2.13, was 0.2.14.
   Constraints on package "react-meteor-data":

   To allow potentially incompatible changes to top-level dependencies, you must
   pass --allow-incompatible-update on the command line.
```

**Comment by mkermath** [comment]
I've recently run into the same error message in the meteor/react/todos tutorial. It appears that the client does not recognize the PropTypes object in the new version of react. I was able to fix this by running the command, "meteor npm install prop-types"; however the warning message is still there.

**Comment by pilarArr** [comment]
I just updated to React 16 and I get this terminal warning:

```bash
W20170930-13:04:25.602(2)? (STDERR) WARNING: npm peer requirements (for react-meteor-data) not installed:
W20170930-13:04:25.830(2)? (STDERR)  - react@16.0.0 installed, react@15.x needed
W20170930-13:04:25.836(2)? (STDERR)
W20170930-13:04:25.840(2)? (STDERR) Read more about installing npm peer dependencies:
W20170930-13:04:25.841(2)? (STDERR)   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20170930-13:04:25.842(2)? (STDERR)
```

**Comment by hwillson** [comment]
@tafelito No, it hasn't been published yet - it should be soon. 

@pilarArr This was fixed in https://github.com/meteor/react-packages/pull/232 and is awaiting publishing.

**Comment by abernix** [comment]
`react-meteor-data@0.2.14` has been published!

**Comment by realyze** [comment]
@abernix are you sure it's been published? `npm show` shows me 0.2.11 is the latest version:
```
     '0.2.11': '2017-10-19T15:00:57.875Z' 
```

**Comment by klaussner** [comment]
@realyze `react-meteor-data` is an [Atmosphere package](https://atmospherejs.com/meteor/react-meteor-data). 🙂 The version on npm is not the official package.

**Comment by realyze** [comment]
@klaussner Ah, that explains a lot. :-) Thanks!
