### ISSUE TITLE
react-meteor-data not passing/updating props

### ISSUE THREAD

**Issue by Lindstrom1989** [meteor/react-packages#220]
Meteor version 1.4.4.1
react-meteor-data version 0.2.9

There seems to be a problem passing the props returned by the container object to the component.
The new props are received but not updated.

Here is a link to a sample repo https://github.com/Lindstrom1989/meteor-react-data-issue

**Comment by klaussner** [comment]
You are missing a `return` in the `render` function of `CollectionList`:

```js
{this.props.list.map(listItem => {
  <li>{listItem.text}</li>
})}
```

should be

```js
{this.props.list.map(listItem => {
  return <li>{listItem.text}</li>
})}
```

**Comment by Lindstrom1989** [comment]
Gah how embarrassing, thank you.
