### ISSUE TITLE
Repo health check

### ISSUE THREAD

**Issue by hwillson** [meteor/react-packages#221]
While prepping for the release of PR #217, we've done an overall health review of the full `react-packages` repo. A few quick notes:

- Now that Meteor has full npm support, the [`react`](https://github.com/meteor/react-packages/tree/devel/packages/react) and [`react-runtime`](https://github.com/meteor/react-packages/tree/devel/packages/react-runtime) packages are no longer necessary, and can be deprecated.
- While both the [`react-meteor-data`](https://github.com/meteor/react-packages/tree/devel/packages/react-meteor-data) and [`react-template-helper`](https://github.com/meteor/react-packages/tree/devel/packages/react-template-helper) packages are currently valid and in use, `react-meteor-data` is by far the more popular package, and will likely see updates more frequently than `react-template-helper`. The current `react-packages` publishing process only covers publishing all packages in this repo at the same time however. This was done to make sure version numbers were all kept in synch, but now that `react` is handled via npm, this appears to be no longer necessary. The publishing process should be revisited, now that it can be simplified.
- All package test apps needs to be fixed/updated. They're using older versions of Meteor, and don't appear to be working properly. Package documentation should also be updated to outline how to use the tests (since they're run as standalone Meteor apps).
- Actually, now that there are really only two packages left in this repo that are active, and they don't depend on each other (or other packages from this repo in any way), we might want to consider splitting these packages out into their own individual repos.

**Comment by filipenevola** [comment]
I'm closing this just because it's too old. We can open new issues for items that are still valid.

Most of these items were solved already or replaced by new strategies (like hooks)
