### ISSUE TITLE
react-meteor-data v0.2.11 breaks backwards compatibility

### ISSUE THREAD

**Issue by djules75** [meteor/react-packages#223]
In the latest 0.2.11: the global ReactMeteorData variable is exported as 'undefined'.
Which breaks old code relying on the global ReactMeteorData mixin and React.createClass with getMeteorData().

**Comment by hwillson** [comment]
Thanks for reporting this @djules75 - we'll look into this further. To keep using the mixin approach, stay version pinned at 0.2.9 (for now anyways).

**Comment by hwillson** [comment]
I've submitted PR #224 to help with this.

**Comment by maabed** [comment]
+1

**Comment by abernix** [comment]
A beta has been published with the fix provided by @hwillson in #224.  Please help test it prior to its official release to see if it fixes this problem!

    meteor add react-meteor-data@0.2.12-beta.0

**Comment by ycpatel813** [comment]
Hi abernik,
react-meteor-data@0.2.12-beta.0 is not working with Meteor 1.5.
[image]

got undefinde.
Thanks.

**Comment by hwillson** [comment]
Thanks @ycpatel813 - @abernix, it doesn't look like the #224 changes are included in the `0.2.12-beta.0` release.

**Comment by abernix** [comment]
Sorry about that; that is definitely the case.  I've republished with `meteor-react-data@0.2.12-beta.1`, if you don't mind trying again @ycpatel813.

(Leaving this open until it's confirmed working.)

**Comment by hwillson** [comment]
`0.2.12-beta.1` works well for me @abernix, thanks!

**Comment by maabed** [comment]
`react-meteor-data@0.2.12-beta.1` works for me. 👍

**Comment by pozylon** [comment]
react-meteor-data@0.2.12-beta.1 is solving all deprecation warnings and works perfectly with my app which uses react-meteor-data extremely often throughout the whole app.

**Comment by abernix** [comment]
Awesome!  I've gone ahead and published an official `react-meteor-data@0.2.12` package!  Thanks very much for everyone's assistance and feedback/testing on this and especially @hwillson for the fix!

**Comment by denzils** [comment]
Hi so I did `meteor add react-meteor-data@0.2.12`, but I am still getting the warning: `Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class`

Was I supposed to change what I'm importing and if so, to what?
`import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import { Meteor } from 'meteor/meteor';
import { createContainer } from 'meteor/react-meteor-data';
import { HTTP } from 'meteor/http';`
