### ISSUE TITLE
The react-meteor-data module in npm is out-of-date

### ISSUE THREAD

**Issue by j18ter** [meteor/react-packages#229]
The react-meteor-data package one can install via "meteor add" has a fix for this warning:

`"Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class"  modules.js:1534:7`

The corresponding npm module is an older version and still produces the above warning. Can the npm registry be refreshed with the latest version? This is needed to avoid the warning with modules like react-redux-meteor-data, which depend on react-meteor-data via npm.

**Comment by klaussner** [comment]
`react-meteor-data` on npm is not an official package. You should create an issue here instead: https://github.com/jedwards1211/react-meteor-data. 🙂

**Comment by j18ter** [comment]
Thanks for explaining. Have raised an issue for the inofficial NPM moule as suggested: [Need fix from official package to prevent warning](https://github.com/jedwards1211/react-meteor-data/issues/5), and also suggested that react-redux-meteor-data should consider depending on the official package: [Depends on inofficial react-meteor-data module](https://github.com/tempik/react-redux-meteor-data/issues/1)
