### ISSUE TITLE
Tutorial places app in document.body

### ISSUE THREAD

**Issue by AdamBrodzinski** [meteor/react-packages#23]
Putting the root React app into `document.body` can cause a lot of unforeseen problems with browser extensions and other JS that append to body. [The tutorial](https://github.com/meteor/react-packages/blob/master/docs/tutorial.md#step-2-adding-your-first-component) shows you how to render to body. Should we change this or at least provide a warning to not do this in production?

Perhaps something like:

```
<body>
  <div id="root"></div>
</body>
```
and
```
if (Meteor.isClient) {
  Meteor.startup(function () {
    React.render(<App />, document.getElementById('root'));
  });
}     
```

**Comment by stubailo** [comment]
Good point - if you submit a PR I'll accept it, or I'll get to it a bit later.

**Comment by AdamBrodzinski** [comment]
Sure thing, i'll submit one tonight.
