### ISSUE TITLE
react-template-helper warning when using with React 16

### ISSUE THREAD

**Issue by aermler** [meteor/react-packages#237]
I'm using Meteor 1.5.2.2 with react-template-helper 0.2.9 and updated to React 16. I now get the warning:

    WARNING: npm peer requirements (for react-template-helper) not installed:
     - react@16.0.0 installed, react@15.x needed
     - react-dom@16.0.0 installed, react-dom@15.x needed
    
    Read more about installing npm peer dependencies:
      http://guide.meteor.com/using-packages.html#peer-npm-dependencies

I think it is similar to #232.

**Comment by aermler** [comment]
Added pull request #238, similar to #232.

**Comment by sprohaska** [comment]
Could someone merge the pull request and publish a release? It's a bit annoying that react-template-helper prints meaningless warnings with React 16.

**Comment by abernix** [comment]
I've done so. Thanks!  Closing as resolved with #238.  Thanks, @aermler! (and @sprohaska for the ping).
