### ISSUE TITLE
Do you still need react-addons-pure-render-mixin?

### ISSUE THREAD

**Issue by merlinpatt** [meteor/react-packages#239]
The guide recommends installing react-addons-pure-render-mixin alongside the react-meteor-data package, but it doesn't look like it is used anywhere.

Can this be installed without the mixin?

If not, why not? And what needs to be done to remove the need for the mixin?

**Comment by StorytellerCZ** [comment]
Doesn't look like it according to the [docs here](https://github.com/meteor/react-packages/blob/devel/packages/react-meteor-data/README.md). So I guess that the guide is outdated.

**Comment by lorensr** [comment]
Unused according to @leocavalcante 

https://github.com/meteor/react-packages/commit/cead57f6a3164ec22e42aff404111c6f057b0e9b#diff-202c751ad5c80318dca2203793fbd382

**Comment by leocavalcante** [comment]
Mixins isn't a React pattern anymore as of the deprecation of `React.createClass` you should consider the hihg-order component pattern. [1]
`pure-render-mixin` represents a shallow comparison that could be accomplished with `React.PureComponent` now. [2]

[1] https://reactjs.org/blog/2016/07/13/mixins-considered-harmful.html
[2] https://github.com/meteor/react-packages/blob/devel/packages/react-meteor-data/ReactMeteorData.jsx#L177
