### ISSUE TITLE
No Support React 16.2 Fragment Syntax

### ISSUE THREAD

**Issue by stolinski** [meteor/react-packages#241]
Getting errors when using the new `<></>` syntax for fragments caused by bable-runtime package version.

**Comment by abernix** [comment]
Thanks for filing an issue.  Did you get this solved?  Curious if you accidentally closed this since it was 2 minutes after you opened it. :)

If there was anything tricky about  it, please report it here for future developers!

**Comment by klaussner** [comment]
The new [fragment syntax](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html#babel) only works with Babel 7. https://github.com/meteor/meteor/pull/9440 :eyes:

**Comment by benjamn** [comment]
@klaussner Good to know!

**Comment by benjamn** [comment]
Funny that Babel 7 is still in beta, but the React team decided to ship fragments anyway. I'm going to take that as a sign that we can ship Meteor 1.6.1 with Babel 7 beta, too! 😝

**Comment by stolinski** [comment]
Sorry, I had closed this once I realized that it was a Babel Beta version. I should have communicated that. Glad to hear 1.6.1 will include Babel 7 beta!

**Comment by copleykj** [comment]
Pretty sure this can be closed at this point. :smile:
