### ISSUE TITLE
componentWillMount vs componentDidMount

### ISSUE THREAD

**Issue by crapthings** [meteor/react-packages#242]
https://github.com/meteor/react-packages/blob/devel/packages/react-meteor-data/ReactMeteorData.jsx#L127

componentWillMount vs componentDidMount

what is different between

```javascript
componentWillMount() {
  this.data = {};
  this._meteorDataManager = new MeteorDataManager(this);
  const newData = this._meteorDataManager.calculateData();
  this._meteorDataManager.updateData(newData);
}
```

```javascript
componentDidMount() {
  this.data = {};
  this._meteorDataManager = new MeteorDataManager(this);
  const newData = this._meteorDataManager.calculateData();
  this._meteorDataManager.updateData(newData);
}
```

if we use react-router or flow-router + react-mounter then we make a subscribe withTracker

when switching route, next component's componentWillMount will happen before previous component's componentWillUnmount. is this a correct behavior?

this will cause minimongo's remain previous subscription's records, it reruns component while previous records are removed one by one.

the ddp message is always show
sub first then unsub

![image](https://user-images.githubusercontent.com/1147704/34431454-439920e6-ecaa-11e7-9f7a-5eea08a63c8e.png)

this will cause unwanted rerun, screen flick.

then i try to make a container like what react-meteor-data does then move subscribe to "componentDidMount" and "componentWillUnmount" to stop tracker first and subscribeHandler

![image](https://user-images.githubusercontent.com/1147704/34431491-abe5c1ea-ecaa-11e7-84f9-f9f8a549df8a.png)

![image](https://user-images.githubusercontent.com/1147704/34431519-e3e4ed1e-ecaa-11e7-8c7f-1208f330c2ee.png)

the order looks good now, and stop subscribe does what meteor docs said

![image](https://user-images.githubusercontent.com/1147704/34431568-2bb7a3a2-ecab-11e7-9707-76f32add2450.png)

> stop()
Cancel the subscription. This will typically result in the server directing the client to remove the subscription’s data from the client’s cache.

**Comment by crapthings** [comment]
some issue relative to this.

Clean client side minimongo?
https://github.com/meteor/meteor-feature-requests/issues/242

**Comment by dburles** [comment]
@crapthings PR definitely welcome 😊

**Comment by filipenevola** [comment]
closing because of react-meteor-data@2.0.0 https://github.com/meteor/react-packages/pull/273
