### ISSUE TITLE
Upgrade check-npm-version to latest

### ISSUE THREAD

**Issue by alexismoreau** [meteor/react-packages#246]
As we have discussed in the Meteor 1.6.1 milestone (see https://github.com/meteor/meteor/pull/9274#issuecomment-356717362), can you upgrade the check-npm-version package to the latest (0.3.2) since the pull request has been merged ? (see  https://github.com/tmeasday/check-npm-versions/pull/20)

Thank you

**Comment by hwillson** [comment]
PR #247 should address this - thanks!
