### ISSUE TITLE
 Unsafe lifecycle methods were found within a strict-mode tree

### ISSUE THREAD

**Issue by nicubarbaros** [meteor/react-packages#256]
componentWillMount: Please update the following components to use componentDidMount instead: ReactMeteorDataComponent

componentWillUpdate: Please update the following components to use componentDidUpdate instead: ReactMeteorDataComponent

Following errors with react 16.3 and above

**Comment by StorytellerCZ** [comment]
Now these warning are visible outside of strict mode as well due to upcoming React 17.

**Comment by filipenevola** [comment]
closing because of react-meteor-data@2.0.0 https://github.com/meteor/react-packages/pull/273
