### ISSUE TITLE
View doesn't correspond to a template? body

### ISSUE THREAD

**Issue by stubailo** [meteor/react-packages#26]
I don't think the React template inclusion works directly inside `body`:

https://www.dropbox.com/s/p9ghwecxywlr2yf/Screenshot%202015-06-27%2015.33.44.png?dl=0

**Comment by buduguru** [comment]
See the 2nd tip here, maybe it will help https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375

**Comment by stubailo** [comment]
@buduguru I think I know the issue, it's something that @avital was working on - it doesn't have to do with using React itself, but it comes up when using React in Blaze with the `{{> React` inclusion.

**Comment by buduguru** [comment]
@stubailo oh, I see

**Comment by maartenbusstra** [comment]
I'm getting the same kind of error when trying to render through Iron Router. Any fix or workaround yet?

**Comment by stubailo** [comment]
We are starting a new sprint to fix these issues tomorrow, should happen in the next week or two.

**Comment by maartenbusstra** [comment]
Just to clarify; I'm getting "View doesn't correspond to a template? yield".
If I'm not mistaken, it's due to it trying to get a parent template name while Iron Router's yield isn't really a template.

**Comment by stubailo** [comment]
ah, that is good information! It would be even more awesome if you could provide an example repo so that we can test our fix on it.

**Comment by maartenbusstra** [comment]
More awesomeness ensues!
https://github.com/maartenbusstra/ironrouter-react-issue

Thanks for all your great work.

**Comment by maartenbusstra** [comment]
Managed to get it working with this workaround:
https://gist.github.com/maartenbusstra/0ec24933957cc95d4b27

**Comment by stubailo** [comment]
@avital is this closed now?

**Comment by avital** [comment]
I'm waiting for a second round of review from @dgreensp: https://github.com/meteor/react-packages/commit/c374443234d26b7c3bb31b4f7d649213423025cf#commitcomment-12190505
