### ISSUE TITLE
Support dynamic loading

### ISSUE THREAD

**Issue by alanning** [meteor/react-packages#264]
Currently adding the 'react-template-helper' package will cause Meteor to send down React, ReactDom, etc. in the initial payload even if the React component in question is not loaded until later (via dynamic import).

Verified using the [bundle-visualizer](https://docs.meteor.com/packages/bundle-visualizer.html):
```
$ meteor --extra-packages bundle-visualizer --production
```

Adding `{lazy: true}` to package.js...
```
  api.addFiles(['react-template-helper.js'], 'client', {lazy: true});
```
...resolves this issue as explained [here](https://github.com/meteor/meteor/issues/8745#issuecomment-305639176).

**Comment by filipenevola** [comment]
2.0.1 should fix this https://github.com/meteor/react-packages/blob/devel/packages/react-meteor-data/CHANGELOG.md

**Comment by Fanaticys** [comment]
@filipenevola  This changes breaks when you use ardatan:webpack package.

**Comment by filipenevola** [comment]
Hi @Fanaticys could you open a new issue?

**Comment by Fanaticys** [comment]
@filipenevola #293
