### ISSUE TITLE
Turning react-meteor-data to a React hook

### ISSUE THREAD

**Issue by fawzisf** [meteor/react-packages#267]
i thinks it is possible to ditch the HOC in favor of the new hooks, https://reactjs.org/docs/hooks-overview.html#-building-your-own-hooks
this would make the code much easier to maintain and share.
what do you think ?

**Comment by fawzisf** [comment]
#263 looks really promising in this direction.

**Comment by dburles** [comment]
Absolutely. It’s being tracked at #262

**Comment by filipenevola** [comment]
closing because of react-meteor-data@2.0.0 https://github.com/meteor/react-packages/pull/273
