### ISSUE TITLE
React package and a React-mixin package

### ISSUE THREAD

**Issue by ccorcos** [meteor/react-packages#27]
Its very frustrating to me how there's not a single package that gives me React without some side-effects and additional code that I'm not going to use. 

I think there should be one React package that adds React and gives you a JSX compiler (the compiler doesnt add any code to the client so thats fine). Then for whatever mixins you want to make, you can create another package. Otherwise, people are stuck with those mixins and people like me who don't use any meteor data mixins have to create their own packages without all the baggage.

**Comment by stubailo** [comment]
You should check out the guide, the first page tells you exactly how to do
that.

**Comment by ccorcos** [comment]
Ah. perfect! :)
