### ISSUE TITLE
How can one use react-data 2.0.x with the meteor 1.9beta?

### ISSUE THREAD

**Issue by gotjoshua** [meteor/react-packages#279]
When I do meteor update --all-packages
it mentions that 2.0.1 is available but refuses to update it.

Is it really not compatible or is there a trick to get it installed?

**Comment by copleykj** [comment]
This is likely caused by another package having a dependency on an older 0.2.x version. If you read the error message in the console, it should tell you which package has the conflicting version constraint.

**Comment by gotjoshua** [comment]
Here is the exact message:
```
The following top-level dependencies were not updated to the very latest version available:
 * jquery 1.11.11 (3.0.0 is available)        
 * react-meteor-data 0.2.16 (2.0.1 is available)
```

Doesn't seem to mention which one...
`meteor list --tree` shows this:
```
react-meteor-data@0.2.16                      
├── ecmascript@0.14.0-rc190.2 (top level)     
├─┬ tmeasday:check-npm-versions@0.3.2         
│ └── ecmascript@0.14.0-rc190.2 (top level)   
└── tracker@1.2.0 (top level) 
```

Found this in a forum post:
`for p in `meteor list | grep '^[a-z]' | awk '{ print $1"@"$2 }'`; do echo "$p"; meteor show "$p" | grep -E '^  [a-z]'; echo; done`
it indicates there are no direct dependencies on that explicit version:
```
react-meteor-data@0.2.16*
react-meteor-data@0.2.16*: not found
```

`meteor update react-meteor-data` says:
The specified packages are at their latest compatible versions.

When I change the version explicitly in .meteor/packages to this:
`react-meteor-data@2.0.1`
and run the update again I get this:
```
=> Errors while upgrading packages:           
                                              
While selecting package versions:
error: Potentially incompatible change required to top-level dependency: react-meteor-data 2.0.1, was 0.2.16.
Constraints on package "react-meteor-data":
* react-meteor-data@2.0.1 <- top level

To allow potentially incompatible changes to top-level dependencies, you must pass --allow-incompatible-update on the
command line.
```
so then i ran the command with that option and succeeded:
`meteor update react-meteor-data --allow-incompatible-update`

**Comment by gotjoshua** [comment]
so far it doesn't seem to have broken anything, and it did get rid of the react deprecation warnings!

But where does this error come from:
`error: Potentially incompatible change required to top-level dependency: react-meteor-data`
?

It seems to have no direct dependencies and still it is blocked... Any ideas why?

**Comment by CaptainN** [comment]
I have found that sometimes you just have to force it to update. I mostly wanted to mention though that you can override specific version using a post pount in `.meteor/packages`

```
react-meteor-data@2.0.1!
```

**Comment by gotjoshua** [comment]
ok, so with the "post bang" would i not need `--allow-incompatible-update` ?

**Comment by CaptainN** [comment]
That's the idea (there are cases in which I'm not clear about where it doesn't work - but it works most of the time).

**Comment by gotjoshua** [comment]
Thanks!
