### ISSUE TITLE
Browserify Tutorial Throws Error

### ISSUE THREAD

**Issue by AdamBrodzinski** [meteor/react-packages#28]
Perhaps i'm not reading the Browserify tutorial correctly but I tried creating a new project twice just to be sure. Most of it was copy/pasted from the tutorial. ReactRouter is not defined and i'm getting an error in the client console:

`Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value) is not a function`

However if I take out the `app.browserify.options.json` file then it works fine (however i'm assuming it would double load react?)

Any ideas on what I can change? I've uploaded a repo that should reproduce the error:    
https://github.com/AdamBrodzinski/browserify-test

**Comment by stubailo** [comment]
Kill your app, run meteor update, then start it again. I forgot to update
some version dependencies. Will fix tonight.

**Comment by AdamBrodzinski** [comment]
That did it. Thanks!

**Comment by stubailo** [comment]
Fixed conclusively in this commit: bf9976833d75c0d39c6d00198add434005bb2131
