### ISSUE TITLE
Add example for routing with FlowRouter and ReactRouter

### ISSUE THREAD

**Issue by stubailo** [meteor/react-packages#29]
Routing is an important part of any app, we should have a quick guide that shows you how to get set up with these popular tools. It's not any harder than Iron Router, but the absence of a guide makes it seem like it is.

**Comment by arunoda** [comment]
I'll be working on a new project called ReactLayout. Which is very similar to FlowLayout. I'll post here with what we've in few days.

**Comment by stubailo** [comment]
Dude, awesome. What's the status of Flow Router 2.0? Should I be using the 2.0 or 1.0 API in my example code?

**Comment by stubailo** [comment]
Also, have you seen React Router? It has a really cool way of dealing with nested component trees, making it unnecessary to special case "layouts" - they are just like normal components, and the nested components correspond to nested routes.

**Comment by arunoda** [comment]
2.0 is almost ready. Current version is the 2.0 itself. We've deprecated few APIs and added more. But, generally it's a release of stability. Current documentation is valid for 2.x

We'll do it soon. Almost done. Waiting for few more bugs to come and trying with IE8 support.

**Comment by arunoda** [comment]
Yeah! ReactRouter is cool. I don't wanna make Flow like it. That's not what we built it for.
Sometimes it's hard to nested routing in that way. (My personal opinion) and Lower level components should deal with how to nest components. But still it's a set of ideas, but I like React Router's concept.

ReactLayout is just to boot React components to the DOM. We've some ideas to do SSR.

**Comment by stubailo** [comment]
Yeah, it's always good to have multiple options - I think Flow Router will be much simpler to get started with, and just accomplishes the task of routing very simply. I'm glad that you are building things like Layout separately, it's good to have just a simple router available, without a bunch of extra stuff.

**Comment by arunoda** [comment]
ReactRouter is pretty much simple too I guess. May be much simpler than us. One of the best thing with Flow is our reactive API. That'll be very useful when building large apps.

**Comment by Sylanz** [comment]
Nightstrike789 here. I have used FlowRouter a little bit, I like how minimalistic it is. Im excited to see ReactLayout when there is a version available for use.

**Comment by arunoda** [comment]
ReactLayout is here: https://github.com/kadirahq/meteor-react-layout

**Comment by Sylanz** [comment]
From my very first initial preview of ReactLayout, it's pretty awesome when used with Flow Router. Some of my concerns past basic routing have already been addressed by just setting up a very basic app. My test app is here, https://github.com/Sylanz/react_meteor_test. I would try to keep whatever example/guide is used for the tutorial nice and simple such as this.

**Comment by stubailo** [comment]
Yeah the goal for this is to just write a 5-6 line code snippet for each, just to show it's not rocket science.

**Comment by jordangarside** [comment]
Here's a simple example application...

[react demo](http://react-viewport-rendering-demo.meteor.com/) with [source](https://github.com/jordangarside/react-viewport-rendering-demo)
[blaze demo](http://blaze-viewport-demo.meteor.com/) with [source](https://github.com/jordangarside/blaze-viewport-rendering-demo)

React demo has a couple bugs, not sure why at the moment, but they both basically work and have the same functionality.
React demo is done with [Flow Router](https://github.com/meteorhacks/flow-router) and [React Layout](https://github.com/kadirahq/meteor-react-layout).
Will probably test @arunoda's SSR on them when it's released.

**Comment by dcsan** [comment]
@jordangarside cool, using `cjsx` :)

this is a template level subscriptions?

```
	getMeteorData: ->
		results: Items.find().fetch()
```

guess its just a one page right now, so doesn't use the router that much?
are there any instances where you change subscriptions based on URLs?

**Comment by stubailo** [comment]
@dcsan if you use Flow router, you can use that functionality. React router doesn't have any functionality for subscription management, so in that case you should use subscriptions from components.

**Comment by giantelk** [comment]
@stubailo This todo example has subscriptions in the routes file `routes.jsx`, but it's not easy to follow. I'm assuming they are here for startup, but why not put them in the react components, and eliminate some of this complexity?
https://github.com/meteor/react-packages/blob/master/examples/react-todos/client/routes.jsx

**Comment by stubailo** [comment]
Oh wait I don't actually know - I could do the redirect from inside the component... hold on while I fix this

**Comment by stubailo** [comment]
I added some simple examples here: http://react-in-meteor.readthedocs.org/en/latest/routing/

If people want to improve this page, PR this: https://github.com/meteor/react-packages/blob/master/docs/routing.md

**Comment by arunoda** [comment]
I will do a PR once we released FR 2.0 (this thursday)

We may change package namespace. And I am quite not sure about directly
rendering inside FR action.

That's because, DOM may not be ready when it's getting called.

**Comment by stubailo** [comment]
Ah, that's a good point! What's the best way to fix it? Use React layout?

**Comment by arunoda** [comment]
Or. Use meteor startup + tracker.aftetFlush or $().

Better to use ReactLayout.

**Comment by harisvsulaiman** [comment]
Hey,  reactrouter onEnter hook to check loginstate using(Meteor.user()) isn't working!

May because meteor.user() is reactive!

**Comment by daslicht** [comment]
Is there somewhere an comparison between ReactRouter and FlowRouter which makes the decision easier please?

**Comment by casperan** [comment]
flowrouter seems to depend on browserify and that seems to add to slow
builds, so I'm looking into reactrouter which can be installed from npm on
meteor 1.3
