### ISSUE TITLE
Packages are not published yet

### ISSUE THREAD

**Issue by lulato** [meteor/react-packages#3]
when I ran meteor add react

I got :
While adding package react:
error: no such package

**Comment by AdamBrodzinski** [comment]
Did you download the source to your local packages or are you trying to pull it off of Atmosphere? You'll have to wait until they're done with it to use it from there :smiley: 

I would recommend using reactjs:react until they're done. It works great.

**Comment by grigio** [comment]
You have to prefix all your meteor commands with:

PACKAGE_DIRS=/path/to/react-packages meteor add react

Etc..

**Comment by lulato** [comment]
You mean they are still not done? which mean it's still not on the atmosphere package place?

**Comment by grigio** [comment]
This packages work but still arent published in the atmosphere index

**Comment by stubailo** [comment]
Added a disclaimer to the repo subtitle, and appropriate README.

**Comment by lulato** [comment]
I agree @stubailo . A bit misleading at this point.

**Comment by stubailo** [comment]
Good news everyone! The initial versions of all the packages are now published.

Announcement forum post: https://forums.meteor.com/t/preview-of-official-react-support/6150
Check out the guide online: http://react-in-meteor.readthedocs.org/en/latest/
