### ISSUE TITLE
Build easy way to create an app without Blaze

### ISSUE THREAD

**Issue by stubailo** [meteor/react-packages#30]
This will include two things:
1. `meteor-platform-no-ui` - a package that lets you get all of the standard meteor stuff without Blaze
2. `static-html` - a package that lets you render static HTML for your app without using `templating`. Basically, you can create an `index.html` file that has `<head>` and `<body>` tags, and those will be used for the server response. You can use this to render a container element for your React components, modify the meta tags of your page, etc.

This is _not_ an implementation of server-side rendering; the `static-html` package will always render the same HTML, which should be filled in with content on the client side. Server side rendering will be discussed here: https://github.com/meteor/react-packages/issues/15

**Comment by gabrielhpugliese** [comment]
:+1:

**Comment by stubailo** [comment]
After talking with @avital, I've decided that it would be best to ship this as part of Meteor 1.2 (and not before) in order to take advantage of the ongoing work on build system improvements.

**Comment by ccorcos** [comment]
:+1:

**Comment by webyak** [comment]
+1

**Comment by stubailo** [comment]
This is done now as of Meteor 1.2. You just need to do:

```sh
meteor remove blaze-html-templates
meteor add static-html
```

voila!
