### ISSUE TITLE
Warning message in console when using withTracker in version 2.2.0

### ISSUE THREAD

**Issue by rj-david** [meteor/react-packages#311]
When using version 2.2.0, for a page using withTracker, we are getting this error in the console

```
Warning: useTracker expected an array in it's second argument (dependency), but got type of undefined.
```

**Comment by filipenevola** [comment]
Hi @rj-david, I see it.

@CaptainN removed from the condition a check for falsy values in this commit https://github.com/meteor/react-packages/commit/fd8e02fef66024a22079aa391a74ec9e115c315c.

<img width="1654" alt="Rework useTrackerWithDeps and others · meteor:react-packages@fd8e02f 2021-01-20 13-16-27" src="https://user-images.githubusercontent.com/437372/105210676-bd206f80-5b21-11eb-95a8-69a07f3bc77a.png">

Was this on purpose? If so we should document this change.

Maybe the change was to keep it consistent with React useEffect but let's wait for @CaptainN here.

**Comment by CaptainN** [comment]
That's a bug. Will fix.

**Comment by CaptainN** [comment]
https://github.com/meteor/react-packages/pull/312

**Comment by filipenevola** [comment]
Hi @rj-david 2.2.1 is published and it fixes this issue.

thanks @CaptainN

**Comment by rj-david** [comment]
Confirming this fix
