### ISSUE TITLE
react-meteor-data 

### ISSUE THREAD

**Issue by DenysOf** [meteor/react-packages#316]
Hi,
react-meteor-data@=2.2.X is introducing an error in the App which worked on react-meteor-data@=2.1.X
component affected: useTracker()
The App react version: "react": "^17.0.1",

```Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.```

Downgrading to react-meteor-data@=2.1.4 works.

<img width="425" alt="Screenshot 2021-02-03 at 17 30 01" src="https://user-images.githubusercontent.com/77796082/106791098-669c5080-664c-11eb-9a57-fcbdef9e64e1.png">

**Comment by CaptainN** [comment]
Can you confirm that this is still a problem in 2.2.2?

Can you also provide a reduction?

**Comment by DenysOf** [comment]
All good now, thanks @CaptainN!

Can you clarify on reduction, please?

**Comment by DenysOf** [comment]
@CaptainN, sorry, looks like still a problem on 2.2.2

Can you please clarify on reduction?

**Comment by CaptainN** [comment]
A reduction is a reproduction of the problem from larger code base, which clearly demonstrates the problem.

I suspect the problem you are having is pretty much what that error is describing - that something in your deps array is changing on every render. But it might help me work out a mitigation strategy if I had a reproduction. It might also help me point out some alternative ways to work with the hook in a way which doesn't trigger the error.

**Comment by filipenevola** [comment]
Hi @DenysOf, you could read more about reproductions [here](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor)

**Comment by DenysOf** [comment]
> Hi @DenysOf, you could read more about reproductions [here](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor)

Yes, I'm aware of re-production, just didn't thinking its a typo `reduction` .

**Comment by DenysOf** [comment]
Sorry, for delay, have been crazy busy with other stuff.
Please see below:

`const useBStats = () =>
  useTracker(() => {
    const subscription = Meteor.subscribe("BlockRaw");
    const bStats = BlockRaw.findOne({}, {sort: {blockHeight: -1}});
    const meteorStatus = Meteor.status();
    passed = false;
    return {
      bStats: bStats,
      isLoading: !subscription.ready(),
      meteorStatus: meteorStatus,
    };
  }, []);
const useStats = () =>
  useTracker(() => {
    const subscription = Meteor.subscribe("ValidatorStats");
    const stats = ValidatorStats.findOne({}, {sort: {blockHeight: -1}});
    const meteorStatus = Meteor.status();
    passed = false;
    return {
      stats: stats,
      isLoading: !subscription.ready(),
      meteorStatus: meteorStatus,
    };
  }, []);
const useDelegators = (account_ids, numRec) =>
  useTracker(() => {
    const subscription = Meteor.subscribe("Delegators", account_ids);
    const delegators = Delegators.find({}, {limit: numRec}).fetch();
    const meteorStatus = Meteor.status();
    passed = false;
    return {
      delegators: delegators,
      isDelegatorsLoading: !subscription.ready(),
      meteorStatus: meteorStatus,
    };
  }, [account_ids]);`

I have more then one useTracker hook in one component, is this a problem?

**Comment by DenysOf** [comment]
@CaptainN @filipenevola have made an effort and amalgamated all into one useStats function (many subscriptions in one useTracer block), but it didn't help.

**Comment by CaptainN** [comment]
A reduction is part of a reproduction. The distinction is not that important. Sorry if that was a little bit of esoteric jargon.

**Comment by CaptainN** [comment]
If you could provide a little more context (the use of those hooks) that might help. For example, depending on how `useDelegators` is called, this code may not work, because the `account_ids` array may be getting a fresh reference on every render.

**Comment by DenysOf** [comment]
> If you could provide a little more context (the use of those hooks) that might help. For example, depending on how `useDelegators` is called, this code may not work, because the `account_ids` array may be getting a fresh reference on every render.

Thanks for clarifying `reduction` always great to learn something new :)

Sure, see below,

 const {**delegators**, isDelegatorsLoading} = useDelegators(a, stateCtx.config.lastEpochs);`

``` if (!isDelegatorsLoading && delegators) {
      let t = [];
      for (const d of delegators) {
        t.push(d.pool)
      }
....
```
hope this helps

**Comment by CaptainN** [comment]
>      let t = [];
>      for (const d of delegators) {
>        t.push(d.pool)
>      }

So that's it exactly - that array instance is getting refreshed on every render, which is pretty much exactly what the error is telling you is happening: 

Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, **or one of the dependencies changes on every render.**

This issue has come up a lot in my teams with `useEffect` and `useTracker` - enough that I'm going to make a change to the `useTracker` docs, and recommend that _deps_ not be used by default. They are _optional_ with `useTracker` anyway. Supplying _deps_ should be thought of as an optimization step, and not a standard practice with `useTracker`.

The specific way _deps_ optimize useTracker is worth understanding too - it only really helps with renders after mount, by pulling the computation out of the render (react) fiber (a single execution frame). That's not always going to be faster than just running your Meteor work right in the render.

**Comment by DenysOf** [comment]
Many thanks for detailed research. I have removed  the deps and its now working with ```react-meteor-data  2.2.2```

Had to apply workaround, as one of the dep, is changing on user input and should re-render and refresh computation with different parameter `const subscription = Meteor.subscribe("Delegators", account_ids);`  Working now until I find a better solution. `account_ids` was in the den array, causing re-render.
