### ISSUE TITLE
useTracker not updating // parallel executions?

### ISSUE THREAD

**Issue by thomasf1** [meteor/react-packages#325]
I´m getting strange behaviour when trying to display Meteor.user() data like this:

```javascript
const googleEmail = useTracker(() => {if (Meteor.user() && Meteor.user().services.google) {return Meteor.user()?.services.google?.email} else {return "loading..."}})
```

It sometimes displays the email and sometimes not.

Putting some console.logs in and a count each time it executes gives renders the count 3, not 4 as it should.

Debug js:
```javascript
var debugData = useTracker(() => {runcount = runcount + 1; console.log('useTracker ran', Meteor.user(), runcount, Meteor.user()?.services.google?.email); return runcount})
```

Console output:
```javascript
useTracker ran undefined 1 undefined
useTracker ran undefined 2 undefined
useTracker ran {_id: "29839283", profile: {…}, services: {…}} 3 undefined
useTracker ran {_id: "29839283", profile: {…}, services: {…}} 4 some@email.com
```

HTML rendered: 3 as runcount and no email

Any idea on how I could dig deeper?

**Comment by CaptainN** [comment]
I'm not sure what you are trying to do here, but there is a startup period for `Meteor.user()`. If `Meteor.user()` returns `undefined` (instead of an object or `null) it means it's still initializing. You'll need to work around that.

**Comment by CaptainN** [comment]
Also checkout: [`Meteor.loggingIn()`](https://docs.meteor.com/api/accounts.html#Meteor-loggingIn)

**Comment by thomasf1** [comment]
Yes, I´m aware that I need to work around Meteor.user() returning undefined.

I´m trying to display Meteor.user()?.services.google?.email. Unfortunately that fails sometimes. Apparently the Meteor.user() triggers useTracker 4 times. Unfortunately somehow it just returns the information from the 3rd run somehow. I´m having a hard time understanding that behaviour.

**Comment by filipenevola** [comment]
@thomasf1 I don't think you should publish all your services to the client.

I usually copy the email to the first level of my user document in the `Accounts.onCreateUser` callback.

Maybe you are not publishing the services (which is good) and then your code is failing.

Your issue looks more a question than an issue.

The best place to ask questions is in the [Forums](https://forums.meteor.com) or in our [Community Slack](https://join.slack.com/t/meteor-community/shared_invite/enQtODA0NTU2Nzk5MTA3LWY5NGMxMWRjZDgzYWMyMTEyYTQ3MTcwZmU2YjM5MTY3MjJkZjQ0NWRjOGZlYmIxZjFlYTA5Mjg4OTk3ODRiOTc).

Please send this question there and I'm sure you are going to get some help.

**Comment by thomasf1** [comment]
Publishing some of the services if default behaviour and not really the issue here. Copying the email to the first level could be a workaround for a bug, but the useTracker really should not behave like it does in this instance.

It´s not a question. It´s a simple piece of code running/updating 4 times, but only the result of the 3rd run rendering.

It´s also simple to replicate: Set up a meteor, add react and google-accounts (or use any existing with services) and put in this code:
```
var debugData = useTracker(() => {runcount = runcount + 1; console.log('useTracker ran', Meteor.user(), runcount, Meteor.user()?.services.google?.email); return runcount})
```

Then, render it as such in react.

```
<div>Google: debugData {debugData}</div>
```

Refresh the page.

console output
```
useTracker ran undefined 1 undefined
useTracker ran undefined 2 undefined
useTracker ran {_id: "29839283", profile: {…}, services: {…}} 3 undefined
useTracker ran {_id: "29839283", profile: {…}, services: {…}} 4 some@email.com
```

Rendered:
```
Google: debugData 3
```
It might be some timing issue / race condition, but certainly not the expected behaviour of useTracker
