### ISSUE TITLE
Invalid hook call – react-meteor-data 2.3.2

### ISSUE THREAD

**Issue by cstrat** [meteor/react-packages#339]
https://forums.meteor.com/t/invalid-hook-call-react-meteor-data/56249

Basically anywhere I am using `useTracker` I get this error:

![](https://aws1.discourse-cdn.com/meteor/original/3X/7/7/774e80eea093bf60d16000beade8951928d5ac6b.jpeg)

This bug only appears in version 2.3.2, not in 2.3.1.

I am going to look over the changelog to see if I can find the culprit...

**Comment by cstrat** [comment]
It doesn't look like there were any meaningful changes in 2.3.2...

**Comment by StorytellerCZ** [comment]
Fixed in 2.3.3

**Comment by derwaldgeist** [comment]
Just ran into this when upgrading Meteor 1.10.2 to 2.2.1. It should be mentioned in the 2.2.1 change log that you have to manually upgrade to 2.3.3 afterwards. It's a breaking change IMHO.
