### ISSUE TITLE
Seems like React chrome extension doesn't work with Meteor projects

### ISSUE THREAD

**Issue by pronevich** [meteor/react-packages#35]
Without meteor, using browserify or webpack all works fine, but with meteor I can't see components tree, just only few times have success.

**Comment by stubailo** [comment]
Interesting - I have also noticed that it's sporadic. I thought it was maybe a bug in the chrome extension, but if it's Meteor-specific, then we should investigate.

**Comment by grigio** [comment]
It may be an extension problem
https://github.com/facebook/react-devtools/issues/82
https://github.com/facebook/react-devtools/issues/90

**Comment by dgreensp** [comment]
Run `meteor update` or `meteor update react-runtime` to get the fix, which is in `react-runtime 0.13.3_2`.

**Comment by pronevich** [comment]
tnx, I've tried it. Works fine
