### ISSUE TITLE
Meteor and React V18 incompatibility

### ISSUE THREAD

**Issue by KrisjanisStrods** [meteor/react-packages#355]
After updating react and react-dom version to V18, code-breaking changes are introduced in components that are using `useTracker from 'meteor/react-meteor-data';`. 

What ends up happening is, that component gets infinitely re-rendered.

Before V18 update:
![Working](https://user-images.githubusercontent.com/48338808/160883104-9e981074-f9e0-4a59-97c0-d6174e6939b4.png)

After V18 update:
![NOT_Working](https://user-images.githubusercontent.com/48338808/160883154-d2db9822-d3c2-4197-85c3-218219ca7c4d.png)

Steps to reliably reproduce the found bug are outlined in the following repo:
https://github.com/KrisjanisStrods/meteor-and-react-V18-incompatibility

**Comment by CaptainN** [comment]
This should go with #355

**Comment by KrisjanisStrods** [comment]
Close because of duplicated #354
