### ISSUE TITLE
meteor/react-meteor-accounts module not found

### ISSUE THREAD

**Issue by u4d3rc0v3r** [meteor/react-packages#356]
Install using meteor add react-meteor-accounts with typescript configured

**Comment by StorytellerCZ** [comment]
Do you actually get an error when you try to start Meteor or is it just highlighted by Typescript?

**Comment by henriquealbert** [comment]
the same happens to me, but it is only the TS warning, no problem when building it

**Comment by CaptainN** [comment]
That makes sense. Someone needs to add [the types](https://github.com/meteor/react-packages/tree/master/packages/react-meteor-accounts/types) to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). The package is written in TypeScript, but Meteor doesn't yet support TypeScript directly, so we need to create a @type/react-meteor-accounts package over there.

**Comment by henriquealbert** [comment]
I'll help with that 🙌🏻
