### ISSUE TITLE
ReactMeteorData is not defined

### ISSUE THREAD

**Issue by wontwon** [meteor/react-packages#38]
When trying to include ReactMeteorData as a mixin, the server throws an error saying it was not defined. I had created a new project and installed the react package and react-meteor-data, but no luck.

**Comment by wontwon** [comment]
Does anyone have any insight on this?

**Comment by AdamBrodzinski** [comment]
Could you upload a repo? If so I can check it out. It's working for me (famous last words)

**Comment by wontwon** [comment]
@AdamBrodzinski here's my repo: https://github.com/wontwon/react-td 

I just did the first first part of the tutorial and included ReactMeteorData.

**Comment by wontwon** [comment]
yeah -- tried running it again, but no good. very sad :(

**Comment by wontwon** [comment]
@AdamBrodzinski -- I think I found the problem. When adding the react package to my project, it installs React package 0.0.1 and React Meteor Data package 0.0.1.

**Comment by dropfen** [comment]
Is `ReactMeteorData` defined on the server?

**Comment by AdamBrodzinski** [comment]
When I ran the repo on my machine I received an error on the client saying `Uncaught Error: Expected object returned from getMeteorData`.

After I added this method it works:

```
 getMeteorData() {
    return {
      foo: Session.get('foo')
    };
  },
```

Also to go a step further here's the app.jsx code to serverside render and print the HTML to the console:

```
var App = React.createClass({
  mixins: [ReactMeteorData],

  getMeteorData() {
    // return because Session doesn't exist on Server
    if (Meteor.isServer) return {};

    return {
      foo: Session.get('foo')
    };
  },

	render() {
		return <div>Hello world!</div>;
	}
});

if (Meteor.isClient) {
	Meteor.startup(function () {
		React.render(<App />, document.getElementById('app'));
	});
}

if (Meteor.isServer) {
  var html =  React.renderToString(<App />);
  console.log(html);
}
```

Hope this helps! :beer:

**Comment by wontwon** [comment]
@AdamBrodzinski thanks so much for your help. I think the problem may be local to my machine. This is what I get when I try to run my repo.

Server:

```
 W20150705-13:39:42.753(-4)? (STDERR) ReferenceError: ReactMeteorData is not defined

```

When removing and adding react: 

```
$ mr add react

Changes to your project's package version selections:

babel-compiler      added, version 5.4.7
babel-runtime       added, version 1.0.0
jsx                 added, version 1.0.0
react               added, version 0.0.1
react-meteor-data   added, version 0.0.1
react-runtime       added, version 0.13.3
react-runtime-dev   added, version 0.13.3
react-runtime-prod  added, version 0.13.3


react: Everything you need to use React with Meteor.
```

**Comment by AdamBrodzinski** [comment]
Hmmm that's odd. In the repo it's using meteor-data v0.1.0.... perhaps you need to clean out the Meteor package cache somehow? I'm not sure how to do this except except to blow out the `~/.meteor` directory and re-install. 

Here's what I get when I run add react:

```
foo ⇒  meteor add react

Changes to your project's package version selections:

babel-compiler      added, version 5.4.7
babel-runtime       added, version 0.1.0
coffeescript        added, version 1.0.6
cosmos:browserify   added, version 0.4.0
jsx                 added, version 0.1.0
react               added, version 0.1.1
react-meteor-data   added, version 0.1.0
react-runtime       added, version 0.13.3_1
react-runtime-dev   added, version 0.13.3_1
react-runtime-prod  added, version 0.13.3_1


react: Everything you need to use React with Meteor.
foo ⇒
```

**Comment by wontwon** [comment]
@AdamBrodzinski -- I just tried re-installing meteor and reinstalling react, but same results.

**Comment by wontwon** [comment]
Figured it out! I was exporting a path in my bash profile to my meteor packages which used an older version of react and react-meteor-data. I think this was something I implemented following an tutorial when we couldn't install the react package from atmosphere.

**Comment by stubailo** [comment]
Darn - sorry you ran into this. I guess I will close this issue for now because it's not really related to this set of packages.

It might be useful in general though to warn when a package from `PACKAGE_DIRS` overrides something from Atmosphere? @dgreensp what do you think?
