### ISSUE TITLE
react-template-helper doesn't un-mount React component

### ISSUE THREAD

**Issue by AdamBrodzinski** [meteor/react-packages#4]
Does Meteor automatically clean up the React component that get's rendered in with the `{{React } }` helper? It seems like the current build will leak once it's torn down.

I was going to try and submit a PR but I couldn't figure out a way to reference the node once `onDestroyed` is called since `this.firstNode` is null.

I'm manually doing this with an ID like so and that works:

```
Template.postsNew.rendered = function() {
  var container = document.getElementById('PostContainer');
  React.render(React.createElement(PostForm), container);
};

Template.postsNew.destroyed = function() {
  var container = document.getElementById('PostContainer');
  React.unmountComponentAtNode(container);
};
```

**Comment by avital** [comment]
Hmm. The id approach won't work if you reuse the component. You're right that we need to implement this. It's unfortunate that there's no `beforeDestroyed` hook but maybe there's a way to get around this by accessing the view directly... I'll put this on my list, thanks.

**Comment by avital** [comment]
(See https://github.com/meteor/meteor/issues/2141 for the `beforeDestroyed` feature request)

**Comment by avital** [comment]
Thanks for the pull request, but I found a simpler solution that also doesn't add unnecessary attributes to the DOM.
