### ISSUE TITLE
Packages are missing licenses and copyright notice

### ISSUE THREAD

**Issue by wkeithchau** [meteor/react-packages#401]
The licenses and copyright notices are missing from the repo.
Would these packages be using the same copyright notice as the main Meteor repo? Possible to release new versions with licensing.

**Comment by radekmie** [comment]
Not a lawyer, but _I think_ that the [`"license": "MIT"` line in `package.json`](https://github.com/meteor/react-packages/blob/96313a1afcc41ef9a23c7496470b375e7d357793/package.json#L16) should be enough.

**Comment by StorytellerCZ** [comment]
I do recall a few years back that for corporate people a dedicated license file is needed. Is that correct @wkeithchau

**Comment by wkeithchau** [comment]
Yep, you're spot on @StorytellerCZ .
At least for us, the license file needs to be attached to a published version. If you add a license file now, the current version still isn't valid. A new version needs to be released (I don't believe we can install Meteor packages based off of a GitHub URL/commit?).

**Comment by StorytellerCZ** [comment]
You can copy them locally and use them.

**Comment by wkeithchau** [comment]
Can a new version of the package be created as well?
Our legal is quite finicky. The recently added license cannot be applied retrospectively. We would usually reference a git tag (which looks out-of-sync) or a git commit. The git commit for the latest version (2.7.2) does not include the license file that we need.

**Comment by StorytellerCZ** [comment]
@Grubba27

**Comment by Grubba27** [comment]
Like this? https://github.com/meteor/react-packages/releases/tag/react-meteor-data%402.7.2

**Comment by wkeithchau** [comment]
That will help make referencing the source code easier.
I was thinking more of a version bump (and new version published) since 2.7.2 was released prior to the license being added.

**Comment by wkeithchau** [comment]
At the root directory of the repository is fine.
