### ISSUE TITLE
How to use React Router?

### ISSUE THREAD

**Issue by ccorcos** [meteor/react-packages#41]
React Router looks pretty neat. But I'm trying to figure out how you added it to you project:

https://github.com/meteor/react-packages/tree/master/examples/react-todos

No smart package? :(

**Comment by Slava** [comment]
Have you tried looking at packages.json?

**Comment by AdamBrodzinski** [comment]
@ccorcos Check out the guides. Theres a tutorial on using browserify that uses React-Router as one of the React components to install. http://react-in-meteor.readthedocs.org/en/latest/client-npm/

Also check out my SSR repo, it has a minimal home/about page setup for React-Router (though the server rendering part throws an error on one route)

I don't think wrapping it as a smart package makes sense because there isn't any Meteor functionality. We don't want to wrap the entire react eco-system :smiley:

**Comment by stubailo** [comment]
@ccorcos the guide section above includes how to add ReactRouter to your project. We will also add examples, which is contained in this issue: #29

**Comment by ccorcos** [comment]
The guide looks great. Thanks for this!

**Comment by stubailo** [comment]
No problem! Glad you like it. It's going to get even better soon, I think!

**Comment by ccorcos** [comment]
Sweet!

I'm working on building some React UI components that resemble UITabBarController and UINavigationController. There are some interesting challenges here especially with regards to keeping track of routes, navigation stacks, for different tabs, maintain scroll position, and handling the browser history. 

Any thoughts, ideas, suggestions? Want to help?

**Comment by AdamBrodzinski** [comment]
@ccorcos  Sounds pretty cool! Have you checked out http://reapp.io ? Routing for that is pretty tough.

IMHO if you're going to build a mobile app with React then it's *really* hard to beat React Native. If we can get some help pollyfilling we can run the Meteor JS bundle in React Native (it's mostly event listeners that don't exist).

I wanted to help with this project but am getting bogged down... check it out! https://github.com/hharnisc/react-native-official-meteor-client

**Comment by stubailo** [comment]
@ccorcos I would suggest being router-agnostic, like the folks at [material-ui](http://material-ui.com/#/components/tabs)

I recently built an app with it, and I really appreciated that they had some integration points for a router, but weren't tied to a specific one. I feel like pretty much all of the things you mentioned (scroll position, routes, browser history, etc) should be managed by a global router, and I would rather be able to pick my own or not use one at all.

**Comment by stubailo** [comment]
@ccorcos One thing in particular that would be really awesome is a configurable version of `accounts-ui` for React.

I'm currently working on an official React tutorial for meteor.com, and my stop-gap solution for that step is just using the Blaze one via Blaze.render, but it would be great if there were a native React version that was just as easy to use as the default.

I feel like this stuff is missing from the React community because everyone has a custom login system, but in Meteor that part is standardized so there could be a lot of value in a component like that.

**Comment by ccorcos** [comment]
> Have you checked out http://reapp.io ?

I just checked it out and it looks ok. Seems like overboard for what I want to do though. I don't need all that styled stuff...

> IMHO if you're going to build a mobile app with React then it's really hard to beat React Native. 

I would use React Native, but I'm going to have to build a website as well anyways so it would be really cool if I could reuse everything. That said, we can build something that works well with Meteor, I'm totally game to do the website later. I just want to make sure I can do it all isomorphically within the meteor build system...

> If we can get some help pollyfilling we can run the Meteor JS bundle in React Native (it's mostly event listeners that don't exist).

I'm down to help, but I have no idea what I'm doing when it comes to this side of Meteor. If you can articulate what I have to do, then I'll do it... ;)

**Comment by ccorcos** [comment]
> One thing in particular that would be really awesome is a configurable version of accounts-ui for React.

Honestly, I tend to build all my accounts ui from scratch so I have more control over it. Shouldn't be hard to build this though.

**Comment by AdamBrodzinski** [comment]
> I just checked it out and it looks ok. Seems like overboard for what I want to do though. I don't need all that styled stuff...

Oh yea I agree than. If you just need a few bits it's prob. better to roll your own.

> I'm down to help, but I have no idea what I'm doing when it comes to this side of Meteor. If you can articulate what I have to do, then I'll do it... ;)

Cool! :beers:  Here's some of the info:  cc @hharnisc

https://github.com/facebook/react-native/issues/1495
https://github.com/meteor/meteor/issues/4501
https://twitter.com/SkinnyGeek1010/status/605913483046051840

**Comment by AdamBrodzinski** [comment]
> I just checked it out and it looks ok. Seems like overboard for what I want to do though. I don't need all that styled stuff...

Oh yea I agree than. If you just need a few bits it's prob. better to roll your own.

> I'm down to help, but I have no idea what I'm doing when it comes to this side of Meteor. If you can articulate what I have to do, then I'll do it... ;)

Cool! :beers:  Here's some of the info:  cc @hharnisc

https://github.com/facebook/react-native/issues/1495
https://github.com/meteor/meteor/issues/4501
https://twitter.com/SkinnyGeek1010/status/605913483046051840

**Comment by giantelk** [comment]
Routing get's confusing when deciding on a Meteor router i.e. IronRouter VS
React Router. And server side vs client side routing. Do you have any docs
that can help make the right decision when picking a routing strategy?

On Fri, Jul 10, 2015 at 10:02 AM, Adam Brodzinski <notifications@github.com>
wrote:

> I just checked it out and it looks ok. Seems like overboard for what I
> want to do though. I don't need all that styled stuff...
>
> Oh yea I agree than. If you just need a few bits it's prob. better to roll
> your own.
>
> I'm down to help, but I have no idea what I'm doing when it comes to this
> side of Meteor. If you can articulate what I have to do, then I'll do it...
> ;)
>
> Cool! [image: :beers:] Here's some of the info: cc @hharnisc
> <https://github.com/hharnisc>
>
> facebook/react-native#1495
> <https://github.com/facebook/react-native/issues/1495>
> meteor/meteor#4501 <https://github.com/meteor/meteor/issues/4501>
> https://twitter.com/SkinnyGeek1010/status/605913483046051840
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor/react-packages/issues/41#issuecomment-120416242>
> .
>



-- 

Cheers,
*Flying Horse Dancing*

**Comment by stubailo** [comment]
Let's move this to the relevant issue: #29
