### ISSUE TITLE
meteor add react installs older dependencies

### ISSUE THREAD

**Issue by wontwon** [meteor/react-packages#42]
Currently when running "meteor add react", version 0.0.1 installs instead of version 0.1.0 as well as the older version of the react-meteor-data package. 

How can I go about installing the latest packages? Thanks all :)

**Comment by wontwon** [comment]
related to #38

**Comment by stubailo** [comment]
Closing - it was an issue related to defining `PACKAGE_DIRS` env variable inside the bash profile.
