### ISSUE TITLE
Example Todos: Task text is not reactive

### ISSUE THREAD

**Issue by kevingzhang** [meteor/react-packages#43]
Summary: 
When the task name changed in database, the task name in view doesn't change

Step to reproduce:
Open two browser tab. change a task name in one browser, go to another browser, the name won't change.

Steps done to investigate:
The second browser has received DDP and miniMongo changed.
In TodoItem.jsx the render function set defaultValue like this 
<input
        type="text"
        defaultValue={self.props.task.text}
        placeholder="Task name"
        onFocus={ self.onFocus } 
        onBlur={ self.onBlur }
        onKeyUp={ self.onKeyUp } />

It is always stick on {self.props.task.text} won't change.

I am not sure it is by design or just a fixable bug. I am a new React learner.

**Comment by SenerDemiral** [comment]
#37
