### ISSUE TITLE
Where'd the var go? [Modules]

### ISSUE THREAD

**Issue by giantelk** [meteor/react-packages#48]
Why won't  `var` before the React.createClass() work? i.e. `var AppBody = React.createClass()`

I'm using the `react-todos` example.

Is this on your list to fix? I've got a pile of existing React code that I don't want to have to change.

Also, a bit confused how an NPM React module would work, assuming they use `var` to define `React.createClass()`, but my own (or example) React code won't work.

**Comment by AdamBrodzinski** [comment]
I think AppBody would be file scoped if you use `var`? By leaving out the `var` it makes it a global that is accessible to the whole app.

An NPM React module is typically consumed like webpack or Browserify modules so they wouldn't use a `var` for classes. ES6 modules in Meteor are coming but in the meantime you have to use a global. 

There's also a [guide for using Browserify](https://github.com/meteor/react-packages/blob/master/docs/client-npm.md) and Exposify to import those 3rd party NPM packages into a global namespace. It works rather well!

**Comment by giantelk** [comment]
Check out this React package, they use var before classes. I do the same in
my React code, var before each React class, using require() and Browserify.

For me to make my React code work with Meteor I have to modify a ton of
files. But wouldn't want to also be manually modifying 3rd party React code:

https://github.com/touchstonejs/touchstonejs/blob/master/src/core/ViewManager.js


On Fri, Jul 10, 2015 at 9:30 AM, Adam Brodzinski <notifications@github.com>
wrote:

> I think AppBody would be file scoped if you use var? By leaving out the
> var it makes it a global that is accessible to the whole app.
>
> An NPM React module is typically consumed like webpack or Browserify
> modules so they wouldn't use a var for classes. ES6 modules in Meteor are
> coming but in the meantime you have to use a global.
>
> There's also a guide for using Browserify
> <https://github.com/meteor/react-packages/blob/master/docs/client-npm.md>
> and Exposify to import those 3rd party NPM packages into a global
> namespace. It works rather well!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor/react-packages/issues/48#issuecomment-120411859>
> .
>



-- 

Cheers,
*Flying Horse Dancing*

**Comment by dgreensp** [comment]
We don't currently support `require()` or `import`/`export` in Meteor apps and packages, but it's on our roadmap.  We recognize that developers coming to Meteor from React want this (not to mention the web community at large).

However, you *can* use any npm module that supports browserify.  See: http://react-in-meteor.readthedocs.org/en/latest/client-npm/

On a technical level, `var MyClass = React.createClass(...)` actually means the same thing in Meteor or in npm/webpack: it makes the class local to the file.  The difference is in how you then export the class, which in npm/webpack would be using `exports` or `export`.  In Meteor, the style is currently to use global variables within an app and within a package, and use `package.js` to declare your package exports.

**Comment by giantelk** [comment]
​Thanks, I read all the above.

So if I put my own React code into an NPM module, I won't have to remove
the `var` before my class declarations?​ That could be a nice, short term
hack around.

On Fri, Jul 10, 2015 at 11:03 AM, David Greenspan <notifications@github.com>
wrote:

> We don't currently support require() or import/export in Meteor apps and
> packages, but it's on our roadmap. We recognize that developers coming to
> Meteor from React want this (not to mention the web community at large).
>
> However, you *can* use any npm module that supports browserify. See:
> http://react-in-meteor.readthedocs.org/en/latest/client-npm/
>
> On a technical level, var MyClass = React.createClass(...) actually means
> the same thing in Meteor or in npm/webpack: it makes the class local to the
> file. The difference is in how you then export the class, which in
> npm/webpack would be using exports or export. In Meteor, the style is
> currently to use global variables within an app and within a package, and
> use package.js to declare your package exports.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor/react-packages/issues/48#issuecomment-120430843>
> .
>



-- 

Cheers,
*Flying Horse Dancing*

**Comment by dgreensp** [comment]
@giantelk Yes, although I'm not sure how to make the `cosmos:browserify` package read from the local repo rather than npm.

**Comment by stubailo** [comment]
Someone has a project here that claims to enable modules: https://forums.meteor.com/t/universe-modules-use-es6-es2015-modules-in-meteor-today/6764/3

**Comment by stubailo** [comment]
Created a meta-issue for this: #65
