### ISSUE TITLE
feature request: let you pass in a global React component into react-template-helper without defining a template helper

### ISSUE THREAD

**Issue by AdamBrodzinski** [meteor/react-packages#5]
I'm trying out the latest build of react-template-helper and now that the Component is being passed in by reference it can't be used without passing the template with a helper.

The use case would be just wanting to insert a React component into blaze without passing any data or props into it. In this case you would have to create a JS template helper just to pass in the template name.

However if you use `window[data.component]` then it will be defined at the `onRendered` time. The following code below brings back the ability to pass in the reference or the string name.

Feel free to ignore/close this as I realize this is still a work in progress. I just wanted to chime in since i've been using React and Blaze for bit. I would be more than happy to provide a sample repo and/or a PR if that would help.

Thanks!!

```
Template.React.onRendered(function () {
  var parentTemplate = parentTemplateName();
  var container = this.firstNode.parentNode;

  this.autorun(function (c) {
    var data = Blaze.getData();

    debugger // data.component is undefined at this point if it's the fn

    var comp;
    if (data && typeof data.component === 'string') {
      comp = data && window[data.component];
    } else {
      comp = data && data.component;
    }    
```

**Comment by avital** [comment]
Thanks for trying this package our so early!

Our thought process was that this approach only works well if your react components are defined in your app as opposed to in packages, and there's no way to access package-globals by name programmatically.

But @glasser had a nice idea which is that we could patch spacebars-compiler to treat `{{> React}}` specially. It would let you pass in a variable as opposed to a template helper, so `{{> React component=Dropdown}}` would look for a variable named `Dropdown` if it can't find a helper with that name (I'm not sure about the exact lookup order compared to other places like global helpers). It's worth saying that we want to special case `{{> React}}` anyway to enforce React's "no-siblings-to-react-components rule".

Thoughts @dgreensp, @stubailo?

**Comment by dgreensp** [comment]
@avital I can imagine how to implement Glasser's idea, but it seems super-magical to hack the semantics of the syntax for this particular case.  If you try to make your own helper or template that takes a component as an argument, it won't work.

**Comment by avital** [comment]
I suppose you're right, that's a pretty big piece of magic to add on...

@AdamBrodzinski an important goal is to not make it harder to put react components in packages, and making it easier to use react components defined on the global namespace works against that goal. So I'm inclined to not implement this.

What do you think?

I guess you could also write a global helper called `global` and then use our shiny new subexpression system: `{{> React (global "Dropdown")}}`

**Comment by AdamBrodzinski** [comment]
@avital Ah I don't even know about the subexpression system! Cool !

I agree that making it easy to use globals is a bad pattern :smile:  However it is kind of hard to not use globals without a module system like browserfy/require.

Putting all of your business logic into local packages works too but it feels very cumbersome to do that. (Works *really* well for 3rd party packages though).

For my React/Meteor app i've been putting them in the `client/components/Foo/` folder and then have been using a global `Comp` namespace so at least they're contained in there. By the time the parent renders all the children have been defined.

What would be ideal is (transpiled) ES6 module support for all of Meteor :wink:  

Anyhow, after thinking about it I tend to agree to not allow globals to be used directly.

**Comment by avital** [comment]
Yup, we're talking a lot about ES6 here...

Going to close this ticket then, thanks for the conversation!
