### ISSUE TITLE
call to `{{> React ... }}` missing `component` argument.

### ISSUE THREAD

**Issue by zachdixon** [meteor/react-packages#50]
I'm pretty new to React in the first place, so it may be something I'm doing incorrectly, but here's the issue.

I'm using all the normal meteor react packages, along with meteor-template-helper, and jhartma:cjsx.
I have a component called Header, and when I call `{{> React component=Header }}` in a template, I get this error:
```
Error: In template header, call to `{{> React ... }}` missing `component` argument.
    at null.<anonymous> (react-template-helper.js:14)
    at view.js:191
    at Function.Template._withTemplateInstanceFunc (template.js:437)
    at view.js:190
    at Object.Blaze._withCurrentView (view.js:523)
    at viewAutorun (view.js:189)
    at Tracker.Computation._compute (tracker.js:294)
    at new Tracker.Computation (tracker.js:210)
    at Object.Tracker.autorun (tracker.js:533)
    at Blaze.View.autorun (view.js:201)
```

My template:
```
<template name="header">
  {{> React component=Header }}
</template>
```

I tried emptying out my component of everything except the render function with a basic div and text, same thing. Weird thing is I have another component that works fine, but not sure what's different since I removed everything, and the files are located in the same directories.

Weird thing is, when I call:
```
Template.header.rendered = ->
  React.render <Header/>, @firstNode
```
It works fine.

**Comment by maringerov** [comment]
Hi @zachdixon, did you pass the component with a helper, as suggested in the docs here http://react-in-meteor.readthedocs.org/en/latest/react-template-helper/ ?

**Comment by zachdixon** [comment]
Yep, that's embarrassing :) Completely forgot about that part, thanks.
