### ISSUE TITLE
Syntax errors in React class don't show any file or line #.

### ISSUE THREAD

**Issue by giantelk** [meteor/react-packages#52]
Get incomprehensible errors, i.e. put a semicolon `;` after the last </div> closing tag, that's wrapped inside (); in a React class return(). Get `Uncaught SyntaxError: Unexpected token Y` but no file or line #. Impossible to figure out with even just a few react classes & files.

```
return (
   <div>
      Do something!
   </div>;
 );
```

**Comment by giantelk** [comment]
When building for Android you DO get the file & line #. This may help come up with a fix. 

```
users-MacBook-Pro:react-todos carlf$ meteor run android
Error while running for mobile platforms: Errors prevented bundling:
While building the application:
client/components/AppBody.jsx:118:12: AppBody.jsx: Unexpected token (118:12)
```

**Comment by stubailo** [comment]
@giantelk for `Uncaught SyntaxError: Unexpected token Y` - that's what comes from the browser console; look for the build error in the server-side output, or refresh the browser page. This is just how Meteor currently handles build errors. More discussion here: https://github.com/meteor/meteor/pull/4639

**Comment by giantelk** [comment]
The server console/terminal didn't show any error. Refreshing the browser
just showed the same useless error message.

On Sat, Jul 11, 2015 at 8:07 PM, Sashko Stubailo <notifications@github.com>
wrote:

> @giantelk <https://github.com/giantelk> for Uncaught SyntaxError:
> Unexpected token Y - that's what comes from the browser console; look for
> the build error in the server-side output, or refresh the browser page.
> This is just how Meteor currently handles build errors. More discussion
> here: meteor/meteor#4639 <https://github.com/meteor/meteor/pull/4639>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor/react-packages/issues/52#issuecomment-120673593>
> .
>



-- 

Cheers,
*Flying Horse Dancing*

**Comment by stubailo** [comment]
Here is what it looks like for me:

https://photos-3.dropbox.com/t/2/AABW32X55ACDn5O_lua-bOn-EctvL4YGsp38oDjryQxs7A/12/254212033/png/32x32/1/1436666400/0/2/Screenshot%202015-07-11%2017.12.24.png/CMHvm3kgASACIAMgBCAFIAYgBygC/MVmPmOrUyUchK8vjwh_1njRBWEMlGxn5rBvFPeZU_-o?size=1280x960&size_mode=2

If it doesn't work for you, please submit a reproduction in the form of an entire app so that I can run the exact same thing you are.

**Comment by giantelk** [comment]
I get the correct error msg now in server console & browser window. Yesterday it was definitely NOT showing this. The only difference is I restarted the Meteor app/server in a new terminal. I've seen other similar types of issues with Meteor (strange errors in server console), where restarting the server resolves things.

![screen shot 2015-07-12 at 12 31 16 pm](https://cloud.githubusercontent.com/assets/6137169/8638714/fc3c0224-2891-11e5-985c-ff0928dd1a23.png)
