### ISSUE TITLE
Added jsx package first, then react.  Server-side .jsx file in local package not being transpiled

### ISSUE THREAD

**Issue by ssteinerx** [meteor/react-packages#54]
Within a local package, the following code, unmodified, is callable when the file is named thing.js, but 404's when the file is named thing.jsx.

I have to change the reference from .js to .jsx in the package.js file when I rename the file, the .jsx just never seems to get transpiled server side.

Simply renaming from .jsx back to .js solves the 404 issue.

The file is in a the /server directory, directly off the root of the local package.

```
Meteor.methods(
{
   getConfig: function (siteID, callbackFunction){
    console.log('On Server: getConfig : ' + siteID + ":" + callbackFunction);
    var myConfig = Configs.findOne({"project.siteID": siteID})
    console.log("myConfig: %s", myConfig );
    return (myConfig);
  }
});
```

**Comment by ssteinerx** [comment]
I should mention that the .jsx in the main project is getting transpiled client side just fine.

**Comment by stubailo** [comment]
Have you tried adding JSX as a dependency of your package?

**Comment by ssteinerx** [comment]
@stubailo Worked!  I hadn't tried that -- didn't occur to me that build plugins were separate but I guess they'd have to be so you don't have to mutilate the host app config to use a package using e.g. JSX or Coffee.  Thanks!
