### ISSUE TITLE
2600 LOC React app is super slow running on meteor deploy

### ISSUE THREAD

**Issue by giantelk** [meteor/react-packages#55]
2600 LOC React app is super slow running off server.

I put a React app (with 2600 LOC) into Meteor as per `react-packages`, and it's performance is fine running locally. There is ZERO collections, no user accounts. It's simply React code and images. Mobile design, about 20  screens, very little props or state. 

Just opening a simple side menu React component with only text (no images) is noticeably slower off the server (using Meteor.com free hosting) VS locally. Not sure why, the React code isn't touching the server at all, so why is it so sluggish. I checked in both Chrome (Mac) and the built Android app.

- Carl

**Comment by stubailo** [comment]
This would be a lot easier to investigate if there was a code sample, or a link to the deployed app.

As you said, it doesn't really make sense - there isn't really a clear reason why Meteor would make React slower on the client, so it might be something else about the app that makes this happen.

**Comment by giantelk** [comment]
I found the same issue without Meteor, just using pure Cordova, so posted it on here:
http://stackoverflow.com/questions/31362788/slow-cordova-mobile-app-using-reactjs

**Comment by stubailo** [comment]
OK, going to close it here then since it isn't Meteor-specific.
