### ISSUE TITLE
YouTube embed in iframe won't show or play within React component with Meteor mobile.

### ISSUE THREAD

**Issue by giantelk** [meteor/react-packages#56]
This works with a pure Cordova app, but not when build using Meteor mobile tools. I test on Android 4.4.2

Put this inside your `render` method:

```html
<iframe width="360" height="203" src="https://www.youtube.com/embed/LXBJqmCyOHA" frameborder="0" allowfullscreen></iframe>
```

**Comment by stubailo** [comment]
Have you tried adding `https://www.youtube.com/` here: http://docs.meteor.com/#/full/App-accessRule

Let me know if this works.

**Comment by giantelk** [comment]
No, I'll have to try it out.

On Sat, Jul 11, 2015 at 8:10 PM, Sashko Stubailo <notifications@github.com>
wrote:

> Have you tried adding https://www.youtube.com/ here:
> http://docs.meteor.com/#/full/App-accessRule
>
> Let me know if this works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor/react-packages/issues/56#issuecomment-120673657>
> .
>



-- 

Cheers,
*Flying Horse Dancing*

**Comment by stubailo** [comment]
Any luck?

**Comment by giantelk** [comment]
Not sure when I'll have time to try this.

**Comment by stubailo** [comment]
OK, there is not really a reproduction and it doesn't seem Meteor-specific, so I'm going to close this.
