### ISSUE TITLE
Make ES2015 features more clear for official release

### ISSUE THREAD

**Issue by giantelk** [meteor/react-packages#57]
In React class, render method; can you explain the why of `render() VS render: function()`. 

i.e. Is using `render()` an ES6 feature of object keys pointing to anonymous functions?

**Comment by dgreensp** [comment]
Yup, exactly, it's equivalent but shorter.  Do you think this needs more explanation in the guide or tutorial?

**Comment by giantelk** [comment]
Wouldn't hurt to mention you're using ES6 syntax. Being new to JS and Meteor, Initially I thought it may of been a Meteor specific thing. And on this page I didn't see any hints:
http://react-in-meteor.readthedocs.org/en/latest/jsx/

**Comment by stubailo** [comment]
Isn't there a section about ES6 halfway down the page?

**Comment by giantelk** [comment]
Yes, but I didn't see any mention of this new key/value syntax for
functions. If it's there it isn't obvious.

On Sun, Jul 12, 2015 at 3:43 PM, Sashko Stubailo <notifications@github.com>
wrote:

> Isn't there a section about ES6 halfway down the page?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor/react-packages/issues/57#issuecomment-120756196>
> .
>



-- 

Cheers,
*Flying Horse Dancing*

**Comment by stubailo** [comment]
> Object Consise Method: `var obj = { method() { return 10; } };`

But you're right, we need to make this more clear for Meteor 1.2.

**Comment by giantelk** [comment]
Now I know what to look for I can see the pattern. Problem is when you
don't know what trees look like, you'll never see a forest.

On Sun, Jul 12, 2015 at 6:35 PM, Sashko Stubailo <notifications@github.com>
wrote:

> Reopened #57 <https://github.com/meteor/react-packages/issues/57>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor/react-packages/issues/57#event-353888347>.
>



-- 

Cheers,
*Flying Horse Dancing*

**Comment by stubailo** [comment]
Now that Meteor in general supports ES2015, this issue is no longer specific to this repository.
