### ISSUE TITLE
Semantic UI package from atmosphere doesn't work with React components

### ISSUE THREAD

**Issue by giantelk** [meteor/react-packages#58]
I added the Semantic UI package as per:
`meteor add semantic:ui flemay:less-autoprefixer`

And added the following inside a render(), renaming class to className, but it's not showing the Semantic styling, shows generic browser UI:

    <div className="ui three buttons">
      <button className="ui active button">One</button>
      <button className="ui button">Two</button>
      <button className="ui button">Three</button>
    </div>

Should I be using the React specific NPM package for Semantic UI?
http://semantic-ui.com/introduction/integrations.html

Was hoping to avoid NPM packages were possible and don't mind renaming classes. I got Bootstrap working this way as per Meteor package + React-packages.

**Comment by maartenbusstra** [comment]
Mine is working just fine!

**Comment by stubailo** [comment]
It might help if there were a reproduction in the following style: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor

**Comment by giantelk** [comment]
I got it working, but it appears to be a hack. I had to edit `custom.semantic.json` it wouldn't work out of the box. 

I posted an issue on SO, here:
http://stackoverflow.com/questions/31396500/semantic-ui-only-worked-after-editing-custom-semantic-json-w-meteorjs

**Comment by maartenbusstra** [comment]
@giantelk It is not a hack, it's al explained by the package. Try to read it more carefully before posting issues on irrelevant repos.

If you just want to use semantic-ui without any modifications to themes and the like, use this package instead:
https://atmospherejs.com/semantic/ui-css

You won't have to do any of this configuration, and as an added benefit; your builds will be faster.

**Comment by giantelk** [comment]
Thanks for the tips. The semantic docs for Meteor could be a lot more
clearer IMHO.
