### ISSUE TITLE
react-router: Uncaught TypeError: Cannot read property 'makeHref' of undefined

### ISSUE THREAD

**Issue by giantelk** [meteor/react-packages#59]
Trying to react-router working, I followed the instructions in the docs to add NPM, got my app working with 1 DefaultRoute. But soon as I add a `Link` get this error:
`Uncaught TypeError: Cannot read property 'makeHref' of undefined`

Some code below. btw - Would be awesome to have some docs on how to get react-router working in MeteorJS. 

client/Feedback.jsx
```
var Link = ReactRouter.Link;

MyHeader = React.createClass({
  render() {
    return (
      <div>
      	<Link to="feedback">Feedback</Link>
      </div>
    );
  }
});
```

client/routes.jsx
```
var {
  Route,
  NotFoundRoute,
  DefaultRoute
} = ReactRouter;


var routes = (
  <Route name="root" handler={App} path="/">
    <DefaultRoute handler={App} />
    <Route name="feedback" path="feedback" handler={Feedback} />
    <NotFoundRoute handler={AppNotFound} />
  </Route>
);


var router = ReactRouter.create({
  routes: routes,
  location: ReactRouter.HistoryLocation
});


Meteor.startup(function () {
  router.run(function (Handler, state) {
    var params = state.params;
    React.render(<Handler params={params}/>, document.body);
  });
});
```

client/app.jsx
```
var {
  Link,
  Navigation,
  State,
  RouteHandler
} = ReactRouter;


App = React.createClass({
  render() {
    return (
      <div>
        <MyHeader />
      </div>
    );
  }
});
```

**Comment by giantelk** [comment]
I found the issue, the docs didn't specify to put this file in `client/libs`, I had it off my apps root in `/libs`. Should update the docs, Section 3, here: 
http://react-in-meteor.readthedocs.org/en/latest/client-npm/

**Comment by stubailo** [comment]
@giantelk did you put it in `lib` or `libs`? There is a difference - one is a special Meteor directory, the other is not.

Also, you are filing a lot of issues that turn out to be problems that aren't identifiable from the code snippets. For future issues, can you follow this guide please: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor
