### ISSUE TITLE
muiTheme of context undefined for child component from material-ui

### ISSUE THREAD

**Issue by lourd** [meteor/react-packages#61]
I wrestled with this for a while before figuring out that somehow it's the Meteor version of React that's causing the problem.

I'm rendering a component that uses some components from Material UI, e.g. `<Paper/>`. To set the styling of those components, you have to set `muiTheme` in context. I do this at my top-level component, `App`, like so:

```js
// App.jsx
App = React.createClass({
  childContextTypes: {
    muiTheme: PropTypes.object,
    themeManager: PropTypes.object,
  },

  getDefaultProps() {
    return {
      themeManager: new Material.Styles.ThemeManager();
    }
  },

  getChildContext() {
    return {
      muiTheme: this.props.themeManager.getCurrentTheme(),
      themeManager: this.props.themeManager,
    }
  },

  render() {...}
}
```

In one part of my app, I render a Paper element:

```js
// GroveCard.jsx
GroveCard = React.createClass({
  propTypes: {
    text: React.PropTypes.string,
  }
  contextTypes: {
    muiTheme: React.PropTypes.object,
  },

  render() {
    return (
      <Paper zIndex={2}/>
        {this.props.text}
      </Paper>
    );
});
```

This has been working fine when using the normal browserified version of react, but when using the react-runtime package it fails with this error:
```js
Warning: owner-based and parent-based contexts differ (values: `undefined` vs `[object Object]`) for key (muiTheme) while mounting Paper (see: http://fb.me/react-context-by-parent)
debug.js:43 Exception from Tracker recompute function: undefined
debug.js:43 TypeError: Cannot read property 'component' of undefined
    at getStyles (http://localhost:3000/packages/client-deps.js?13cafeead7e3aad3bdc018f78d6c11e639290d00:6475:47)
```

And line 6475 of that package, function `getStyles` looks like...

```js
  getStyles: function getStyles() {
    var styles = {
      root: {
        backgroundColor: this.context.muiTheme.component.paper.backgroundColor,
        transition: this.props.transitionEnabled && Transitions.easeOut(),
        boxSizing: 'border-box',
        fontFamily: this.context.muiTheme.contentFontFamily,
        WebkitTapHighlightColor: 'rgba(0,0,0,0)',
        boxShadow: this._getZDepthShadows(this.props.zDepth),
        borderRadius: this.props.circle ? '50%' : this.props.rounded ? '2px' : '0px'
      }
    };
    return styles;
  },
```

This error happens anywhere I use a component from Material. My hunch is that this is because React is a peer dependency for Material UI and I'm not declaring that, but I haven't verified that yet.

**Comment by stubailo** [comment]
Have you carefully followed the guide here: http://react-in-meteor.readthedocs.org/en/latest/client-npm/

This happens when you have two copies of React in the same app.

Here is a simple example using material ui: https://github.com/meteor/react-packages/tree/master/examples/material-ui-leaderboard

**Comment by lourd** [comment]
I tried adding the a `browserify.options.json` file and included the recommended `externalify` options, but it doesn't work because I'm bringing in React at the app level and Material at the package level. I do this so I don't have to hack around with where my `browserify.js` file is for load order purposes — I **know** my dependencies will load before all of my app files if I put it in a local package and export the symbols that I need.

**Comment by lourd** [comment]
So it works if I also depend on `react-runtime` package. This is what my package.js file looks like

```js
Package.describe({
  name: 'client-deps',
});

Npm.depends({
  'externalify': '0.1.0',
  // 'react': '0.13.3',
  'react-router': '0.13.4',
  'bowser': '0.7.3',
  'material-ui': '0.9.0',
  'react-tap-event-plugin': '0.1.7'
});

Package.onUse(function(api) {
  api.use([
    'cosmos:browserify@0.3.0',
    'react-runtime',
  ]);

  api.addFiles([
    'the.browserify.js',
    'the.browserify.options.json',
  ], 'client');

  api.export([
    'React',
    'ReactRouter',
    'bowser',
    'Material',
    'injectTapEventPlugin'
  ], 'client');
});
```
And the browserify file

```js
ReactRouter = require('react-router');
bowser = require('bowser').browser;
Material = require('material-ui');
injectTapEventPlugin = require('react-tap-event-plugin');
```

At this point I might as well just use the normal browserified version, it would be less effort.

**Comment by stubailo** [comment]
Ah, looks good. So everything works now? We should probably add this to the guide under some super advanced section.

Hopefully official modules/NPM support will land soon so that we don't have to mess around with this junk anymore.

**Comment by lourd** [comment]
Definitely worth making clear that if you have something in `lib/CoolComponent/CoolComponent.jsx` your browserify dependencies won't be defined, and you'll need to put your `browserify.js` file somewhere like `lib/pretty/please/load/this/file/first/browserify.js`. That's not that advanced of a use case.

**Comment by lourd** [comment]
Or maybe just `lib/lib` will work? Haven't tried that

**Comment by stubailo** [comment]
Yeah, that's a good point. At the end of the day, the Browserify implementation is far from perfect, so I don't know how many of these workarounds we need to document... hopefully we will have first-class support soon

**Comment by lourd** [comment]
Amen to that, looking forward to it :stuck_out_tongue_winking_eye:
