### ISSUE TITLE
can't find defined module

### ISSUE THREAD

**Issue by Zane-XY** [meteor/react-packages#63]
I don't know if I did it right, I'm trying to integrate with Material ui, I can't require the defined exported module.

inside `client/lib/app.browserify.js`,

```
mui = require('material-ui');
injectTapEventPlugin = require('react-tap-event-plugin');
Router = require('react-router');

AppRoutes = require('../components/routes');
```
This gives the following error:

> Error: Cannot find module '../components/routes ' from '/Users/xxx/workspace/app-name/packages/npm-container/.npm/package'

How do I import defined module? the `import ` syntax doesn't work either.

**Comment by stubailo** [comment]
Created a meta-issue for this: #65
