### ISSUE TITLE
using es6 and react: ReferenceError: module is not defined

### ISSUE THREAD

**Issue by Zane-XY** [meteor/react-packages#64]
I'm following this example, https://github.com/meteor/react-packages/tree/master/examples/material-ui-example, after I add a component class, and exported using `module.exports = Master;`, it gives an error `ReferenceError: module is not defined`, why is that?

**Comment by maringerov** [comment]
Did you declare your module as a global variable, e.g. 

```Module = React.createClass({ 
      ... 
    })```

without the `var` keyword?

**Comment by Zane-XY** [comment]
the module was declared in side a es6 class.

**Comment by stubailo** [comment]
Currently we don't support ES6 modules, but we are working on it as soon as humanly possible: http://info.meteor.com/blog/whats-coming-in-meteor-12-and-beyond

**Comment by stubailo** [comment]
Created a meta-issue for this: #65

**Comment by Zane-XY** [comment]
@stubailo Thanks, you guys are great! Is it possible to to just use the snapshot build of  Meteor 1.2 to achieve this?  Would the material ui examples here still be  valid if I am using Meteor 1.2 snapshot build?

**Comment by stubailo** [comment]
No, like it says in the blog post, Meteor 1.2 will _not_ support modules but I would be that 1.3 will.
