### ISSUE TITLE
ES2015 and CommonJS module support

### ISSUE THREAD

**Issue by stubailo** [meteor/react-packages#65]
As mentioned in [this blog post](http://info.meteor.com/blog/whats-coming-in-meteor-12-and-beyond), Meteor currently doesn't support ES2015 modules or CommonJS-style `require` but we will be working on it as soon as possible.

No, module support will not be shipped in Meteor 1.2. However, I expect it will be very soon after.

I'm going to redirect all module-related issues here.

Rest assured that this is absolutely far and away one of our top priorities at the moment.

**Comment by arunoda** [comment]
Is this for requiring Npm modulus or files(modules) in our app ?

**Comment by stubailo** [comment]
I think those can be separated into two different features, but I'm hoping that both will happen at around the same time.

**Comment by grigio** [comment]
`universe:modules` https://github.com/vazco/universe-modules seems a temporary fix to this issue

**Comment by stubailo** [comment]
Going to close this here since it's being worked on as a core Meteor feature.

**Comment by rozzzly** [comment]
@stubailo would you be so kind as to link where that is being tracked? I didn't see anything on the meteor trello, or in the issues for the meteor/meteor repo. Thanks :)

**Comment by stubailo** [comment]
@benjamn we should probably start an issue about this right?

**Comment by eXon** [comment]
If you would like ES6 modules (and more) you can try `webpack:webpack`. You can look at [the example there](https://github.com/thereactivestack/kickstart-simple).

**Comment by rozzzly** [comment]
In addition to ^ I'll link this. https://github.com/vazco/universe-modules/issues/29 They're discussing a package that would hijack the compiler in the same fashion as aformentioned, _but without the webpack dependency._ If MDG wants to avoid the dependency on webpack, this might be a place to start. Without the hard dependency, it'd probably be easier for developers to integrate.
