### ISSUE TITLE
react-runtime-prod does not use proper production build from React

### ISSUE THREAD

**Issue by jedwards1211** [meteor/react-packages#69]
The `react-runtime-prod` package currently uses a browserified version of the NPM `react` package, which is the development version.  The production version available from the React website has several very important features (as described [here](https://facebook.github.io/react/downloads.html))
* Extra performance optimizations (and I believe minifications only possible with human intervention)
* No error messages/warnings (which also improves performance because it's not doing `React.PropTypes` checks.
It is also possible to get the production source into Browserify if you set the environment variable `NODE_ENV` to `production`, but since I assume this is not a convenient way to use Meteor, it would be better to include the pre-built `react-0.13.3-min.js` from their website in the `react-runtime-prod` package.

**Comment by stubailo** [comment]
This certainly used to work. @dgreensp, I think getting rid of envify changes some build settings in React somehow.

@jedwards1211 we're definitely aware of the distinction between dev and prod React, but we need to use Browserify to compile it so that packages like `material-ui` can hook into React sub-modules like `react/lib/invariant`. If we just use the precompiled version from the React website, we will lose that feature.

So it's not about switching away from Browserify, it's just a bug we need to fix.

**Comment by jedwards1211** [comment]
True...but of course (well with Webpack at least, I don't know about in
this setup) I've imported React submodules even though I'm loading a
full production build of React separately, and there's no problem.  I
don't know about the modules some of those package use, but if they're
small, I personally would prefer a bit of code duplication if it's
necessary to use the production build of React.


On Tue, Jul 21, 2015, at 12:11 PM, Sashko Stubailo wrote:
> This certainly used to work. @dgreensp[1], I think getting rid of
> envify changes some build settings in React somehow.


> @jedwards1211[2] we're definitely aware of the distinction between dev
> and prod React, but we need to use Browserify to compile it so that
> packages like material-ui can hook into React sub-modules like
> react/lib/invariant. If we just use the precompiled version from the
> React website, we will lose that feature.


> So it's not about switching away from Browserify, it's just a bug we
> need to fix.


> — Reply to this email directly or view it on GitHub[3].


>



Links:

  1. https://github.com/dgreensp
  2. https://github.com/jedwards1211
  3. https://github.com/meteor/react-packages/issues/69#issuecomment-123405531

**Comment by jedwards1211** [comment]
I do wonder if it's possible to require from a browserified bundle?  If
not, it seems like something that the Browserify folks would be able
implement easily...


On Tue, Jul 21, 2015, at 04:11 PM, Andy Edwards wrote:
> True...but of course (well with Webpack at least, I don't know about
> in this setup) I've imported React submodules even though I'm loading
> a full production build of React separately, and there's no problem.
> I don't know about the modules some of those package use, but if
> they're small, I personally would prefer a bit of code duplication if
> it's necessary to use the production build of React.
>
>
> On Tue, Jul 21, 2015, at 12:11 PM, Sashko Stubailo wrote:
>> This certainly used to work. @dgreensp[1], I think getting rid of
>> envify changes some build settings in React somehow.


>> @jedwards1211[2] we're definitely aware of the distinction between
>> dev and prod React, but we need to use Browserify to compile it so
>> that packages like material-ui can hook into React sub-modules like
>> react/lib/invariant. If we just use the precompiled version from the
>> React website, we will lose that feature.


>> So it's not about switching away from Browserify, it's just a bug we
>> need to fix.


>>


>> — Reply to this email directly or view it on GitHub[3].
>>


>>
>



Links:

  1. https://github.com/dgreensp
  2. https://github.com/jedwards1211
  3. https://github.com/meteor/react-packages/issues/69#issuecomment-123405531

**Comment by stubailo** [comment]
Yeah I think we are aware of the issue, and it is almost definitely fixable. We'll try to get to it soon, and write tests to avoid another regression.

**Comment by stubailo** [comment]
Hey, @jedwards1211 I now suspect you are wrong. I wrote some tests to verify that the builds are correct. I can add more tests if you like, but it seems like the optimizations are there.

f4c1a1dd93f40ca4ba13c37f2ce31be0f9dec836

**Comment by stubailo** [comment]
@jedwards1211 I think it might have been a mistake in the releases. I have just re-published all of the packages, and the newest versions should definitely have the correct dev/prod stuff

**Comment by dgreensp** [comment]
Confirmed in `react 0.1.6`.

**Comment by jedwards1211** [comment]
Yeah, I've learned more since then, apparently the optimizations are all done by UglifyJS removing dead code blocks when process.env.NODE_ENV='production'.
