### ISSUE TITLE
Dev dependencies in material-ui-leaderboard example packages.json

### ISSUE THREAD

**Issue by travischoma** [meteor/react-packages#70]
`externalify` shouldn't be in the packages.json right? This is a dev dependency but not something that should be being built and sent down to the client. I noticed I had a couple dev dependencies in my own project in this file and it was slowing down build/refreshes when I made a change in a jsx file and wanted to see the change asap in the browser.

**Comment by stubailo** [comment]
Hey, so the only things being sent to the client are the modules you require in `app.browserify.json`. Meaning, you don't have to worry about putting extra dependencies in `package.json` if you use them only on the server.

One thing you could try in this particular case is use a pre-built package that someone has published on Atmosphere for `material-ui`: https://atmospherejs.com/izzilab/material-ui

I do agree that build speed could be much improved in the case of NPM modules and Browserify, but we are working on improving build speed in Meteor overall, and there might be some good fixes coming in Meteor 1.2 for those issues.

Eventually, I would expect that we will have first-class support for loading NPM packages on the server and client, and when that comes it will be optimized with regard to build time.

**Comment by travischoma** [comment]
Thanks for the feedback, that's helpful. I found this project template interesting as an alternative using ES6 modules: https://github.com/optilude/meteor-react-example
