### ISSUE TITLE
Subscriptions not re-running?

### ISSUE THREAD

**Issue by jaypanares** [meteor/react-packages#76]
Hi, trying to have my subscriptions update when props have changed:

```
getMeteorData () {
    let data = {};
    let someId= this.props.someId;
    let subs = Meteor.subscribe('published', someId);

    if (subs.ready()) {
      console.log('fetched data');
      data.collection = Collection.find().fetch();
    }
    return data;
  },
```
publications.js
```
Meteor.publish('published', function (someId) {
  return Collection.find({'_id': someId});
});
```
The subscription runs once, but when props change the data doesn't get fetched again (`subs.ready()` is `false` when props change).  I've also tried removing the `if ()` statement, but the published data doesn't change.  What works for now is subscribing to all data and using a find selector to filter out the data set I need (which is not really optimal)

**Comment by stubailo** [comment]
Can you submit a reproduction in the form of an app? The code you have provided should work, so there might be something else that we aren't thinking of that is relevant.

Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by jaypanares** [comment]
Can't seem to currently replicate the issue (maybe it was fixed?).  Anyways, I'll let you know if the issue pops up again.  Thanks!
