### ISSUE TITLE
Request: shouldUpdateForMeteorData() instead of wrapper components

### ISSUE THREAD

**Issue by jedwards1211** [meteor/react-packages#78]
I'm not sure how significant it is, but I'm sure that using wrapper components to implement `shouldComponentUpdate()` for meteor data unnecessarily wastes:
* memory
* CPU cycles
* developer time (I've had to spend more time refactoring a component into a wrapper class with `getMeteorData()` and the wrapped class with `shouldComponentUpdate()` than I would have to spend implementing `shouldComponentUpdate()`)

`reactjs:react`'s `ReactMeteorMixin` didn't have this problem because it channeled all meteor data through the component's `state`, making a drop-in `PureRenderMixin` work well in some cases.

If the `ReactMeteorData` autoruns would merely call a `shouldUpdateForMeteorData(nextData)` to determine if they should `forceUpdate()` or whatever they're doing, it would solve all of these problems.

**Comment by johnsoftek** [comment]
@jedwards1211 This mixin and ReactMeteorMixin both suffer from the same problem: they channel componentWillUpdate through the "data is updated" code path so the two are confused. I have the opposite situation to you: my components have state changes that affect the component's presentation but no corresponding Meteor data changes. The performance impact of find().fetch() on several hundred components is immense.

The mixin needs to allow the component to answer two questions:
* state/props has changed - should I re-do find().fetch()?
* the data has changed - should I trigger a component update?

**Comment by jedwards1211** [comment]
Yeah, there's that problem too.  I really don't think it's a good idea for getMeteorData() to be called every time the component updates.  Wrapper components solve that problem, but it's not a very elegant solution in my opinion

**Comment by lourd** [comment]
> I'm sure that using wrapper components to implement shouldComponentUpdate() for meteor data unnecessarily wastes:
- memory
- CPU cycles
   

------
> The performance impact of find().fetch() on several hundred components is immense.

I would encourage y'all to support your positions with use cases and performance measurements. It's hard for others to reason about what you have in mind without looking at code to support it.

**Comment by stubailo** [comment]
Isn't splitting React components up to have finer-grained control over re-rendering something that you have to do even outside of Meteor? If you are doing complicated stuff inside `render`, you probably want the complicated component to re-render less often than the simple one.

**Comment by jedwards1211** [comment]
There's a difference between splitting up one component into smaller subcomponents and wrapping an already simple component inside other components to reduce re-rendering.  I just don't like all that typing.  Admittedly the performance/memory impact of having wrapper components probably isn't large, but a lot of the overhead that's introduced in programming has to do with less typing and easing development.

The situation I was dealing with was that some of the data in the Meteor collection item associated with a map marker that could change wasn't displayed in the map marker but elsewhere, meaning I wanted the map markers to ignore such changes.  I ended up restructuring my collections as a broader solution to performance problems, but before I settled on that, I was thinking, why should I have to write up a whole wrapper component just to prevent re-rendering if the Meteor data changes weren't relevant to the map marker?  It's not the kind of thing I was used to doing for simple components connected to Flux stores.

What would be the downside of a shouldUpdateForMeteorData() type method?

**Comment by jedwards1211** [comment]
I guess my argument doesn't have much weight though.  It is good to split things into views and controller-views.  I was frustrated with unexpected performance issues at the time I opening this issue, and having to make a rushed prototype of something.  But I've mostly figured it out now.  I'll just close this issue, sorry.

**Comment by stubailo** [comment]
I'm not trying to say that this is a bad feature request :] I'm just trying to poke and prod at it like I usually do to make sure that this new feature is actually a good way of solving the underlying problems. For example, maybe the real solution is to make it much easier to make a wrapper component, or something similar. No need to kill the discussion.

**Comment by jedwards1211** [comment]
Fair enough, well you're doing a good job of poking :)

I'll think about it some more and see if I can come up with a more problematic scenario.  I don't remember exactly how I was trying to do things before I restructured my collections.  But maybe if I think back over it I can come up with a more compelling argument.

**Comment by rclai** [comment]
[This discussion](https://github.com/meteor/react-packages/issues/80) is relevant.

**Comment by jedwards1211** [comment]
Yeah this issue hasn't come up for me anymore...in the current project I'm working on, I'm not even using `MeteorDataMixin`, I'm just putting Meteor data into a Redux store.  In any case I've realized wrapper components are often a useful pattern, as long as there's not too much nested wrapping.

**Comment by skosch** [comment]
I'm in the same boat. My `getMeteorData()` is a 50-line function with multiple `find()`s that depend on one another.

I have a `this.state.index` variable that keeps track of the currently highlighted list item in a certain `<ul>`, and a bunch of things depend on this index.

I'd like to make sure that when a highlighted item is deleted, `this.state.index` doesn't end up pointing to a non-existing item. All it would take is one tiny line in the `getMeteorData()` function, something like `setStateWithoutUpdatingMeteorData({this.state.index: ...});`. This is the simplicity I expect from Meteor; when I was using Blaze nobody was telling me I couldn't update ReactiveVars from within helpers either. Is there absolutely no way of achieving this without creating multiple components?

**Comment by skosch** [comment]
I mean ... one way to defeat the error message is to define a `this.setStateAnyway = this.setState` and use that in `getMeteorData()`. But a cleaner way would be if we actually had a `shouldUpdateForMeteorData()`, and any `setState` inside `getMeteorData()` would (instead of the error) be replaced with a special version that makes that function return false, such that updates would be prevented. Is that a reasonable approach?

**Comment by stubailo** [comment]
I feel like starting to write patterns like this will end up with a huge clump of code inside `getMeteorData`, and your app might be easier to reason about if you split it into different components with fewer responsibilities. It seems like someone editing the component could easily make an edit causing an infinite loop and not catch it for a while.

**Comment by skosch** [comment]
I don't disagree in general, but sometimes (like in this case) it's a dead-simple data display component that just happens to have a complex `getMeteorData`. It's nobody's fault, really; it just happens when your data doesn't perfectly fit Mongo's *denormalize-everything-and-query-by-document* paradigm—I tried my best, but there are some situations when I need to manually join data from across collections etc. This wasn't a problem in Blaze; but the assumptions behind the `getMeteorData` pattern belie the unfortunate reality that sometimes those clumps are inevitable (especially when you're rewriting large apps with existing DB structure). 

Now, splitting that component into two files would (to me, personally) make things *less* neat, because I still have that clump, but with a straggler file on the side, defeating one of the main reasons I like React (one component, one file). Then again, it's perfectly possible that with more React experience I'll soften up to the idea.

I do believe that #91 is significant, and that users should be able to control when re-fetches happen. With such a mechanism in place, `setState` calls from within `getMeteorData` could simply *not* invalidate the Meteor data. Isn't that how Blaze handles reactive changes too?

**Comment by dgreensp** [comment]
> when I was using Blaze nobody was telling me I couldn't update ReactiveVars from within helpers either

I'm pretty sure I've told people that.  Helpers shouldn't update ReactiveVars.

**Comment by skosch** [comment]
Ha! :) The more you know. I don't think I've ever actually tried doing that, but I was under the impression that there were checks in place to stop infinite loops. (Also, that sentence reads way more snarky in retrospect than I had intended for it to be. Sorry!)

I've made a proposal for such a check in #91. It would involve adding a flag `_doNotCallGetMeteorData` (or similar), and then checking for the absence of that flag in the `componentWillUpdate` mixin before proceeding.

**Comment by ffxsam** [comment]
Aha, this explains my issue #113. My function is setting the state on a context object, which triggers `getMeteorData`, which sets the state on context, which triggers `getMeteorData` again, ad infinitum. Bummer. I'm kinda stuck at this point. I need a way for any component to wire a message to the top to say "show the loading spinner with this message." I don't want the added complexity of adding Redux (not to mention I'm not a fan of using browserify or webpack in Meteor projects, as I feel it's more of a Node.js pattern and very un-Meteor-like).

I'm still pondering over how to solve this issue.

**Comment by johnsoftek** [comment]
@Sam Maybe use events. In getMeteorData, trigger an event, say
'data-loading' ,with a message. Spinner listens on event and sets it's own
state to visible. On loading finished, trigger another event, say
'data-loaded'. Spinner should not be a parent of data-fetching component so
state changes won't cascade down.

**Comment by ffxsam** [comment]
I already dove into another solution that works. I'm basically using `ReactiveDict` as a store for app states.

I've got my `Spinner` and `Modal` components at the very top, just because I think it makes less sense to include them in every component that could potentially display a message or show a spinner. That could get really messy.

**Comment by skosch** [comment]
@johnsoftek events work in this case, but they're not really a solution. Is using ReactiveData really the  most elegant way to go? I don't think the need for storing data-dependent state that *doesn't* trigger recalculations is ever going to go away. Should I be looking at Redux?

**Comment by ffxsam** [comment]
@skosch Take a look at [`meteorflux:dispatcher`](https://atmospherejs.com/meteorflux/dispatcher)

**Comment by johnsoftek** [comment]
@skosch "Events work... but they're not really a solution". Contradictory, no?

The Flux concept recommended by Facebook: data flows down through component views; view actions affect data; data changes trigger view refresh...

In this simple case, events achieve a similar result: they don't target a parent but still a view component reacts to a component event. You could use a more formal dispatcher mechanism to mediate the event/listener as @ffxsam suggests.

**Comment by skosch** [comment]
Thanks guys. You're right, Flux/Redux/etc. is absolutely the way to go. I'm in the process of re-writing a relatively large Blaze app though and I was *not* prepared for React's dogmatism on one-way data flow. I'm using a ton of events myself right now, for exactly this reason, and I'm pulling my hair out because that's just really messy, but I also really don't have time to re-architect the entire thing. The ability to use `this.state` without having to worry about infinite loops would de-fang that dogma, for better or for worse.

If that's considered too harmful, then I suppose the take-away is that the requirement for a Flux-like setup needs to be documented much better, so that devs don't fall into this trap to begin with? :)

**Comment by ffxsam** [comment]
I'm curious to know, if you don't wind up using `meteorflux:dispatcher`, how you plan on including Flux or Redux. The only way I've found is to use browserify, which to me feels very hacky in Meteor's ecosystem.

**Comment by skosch** [comment]
Yeah, I've already jumped onto the webpack bandwagon, because I really, really need modularity and lazy loading of arbitrary components (and I needed it yesterday rather than tomorrow, which is why I'm desperate to switch to React). Honestly, it feels like I was shaken out of a wonderful, fantastic Meteor dream back into dark, chaotic Node.js reality, but at least I still have minimongo/ddp/methods/etc.

I may well end up using `dispatcher`, but I'm in the middle of that rewrite, so I'd rather get things working again first before introducing new magic.

**Comment by johnsoftek** [comment]
@skosch You can integrate modules into Meteor: https://github.com/vazco/universe-modules. React/Meteor example: https://github.com/optilude/meteor-react-example. Uses browserify under the hood.

**Comment by skosch** [comment]
Yep, but no lazy loading yet last time I checked, and with webpack you get hot-reload :) With those two features I'd switch back to "pure" Meteor any time.

**Comment by huttonr** [comment]
Not to revive the dead but as this is still an issue with ReactMeteorData, I had been working on a project which struggled on this point, the wrapper components easily became convoluted.

What I came up with as a solution was this: https://github.com/huttonr/react-meteor-computations

While I don't think this is the end-all solution (as if there ever will be one), but it's an interesting idea that I haven't seen in various other Tracker + React solutions.

I hope it helps anyone who is either looking for an alternative to ReactMeteorData, or simply wants some inspiration on how the problem could be solved (but who wasn't satisfied with the other solutions out there).

There's also a [forum post](https://forums.meteor.com/t/alternative-to-reactmeteordata-mixin/17161) if you want to provide any feedback.

**Comment by johnsoftek** [comment]
@huttonr Really interesting solution. I must try it out.

**Comment by tmeasday** [comment]
We are definitely moving *more* in the direction of wrapper components, so I'm going to close this one, unless anyone objects?

**Comment by jedwards1211** [comment]
Yeah, I've had enough experience to recant on my initial performance concerns about wrapper components.  I use `redux-react` a lot and something like its `connect` wrapper/decorator would be a nice alternative to the `ReactMeteorData` mixin.

**Comment by ffxsam** [comment]
Wrappers/higher-order functions are the way to go.

**Comment by tmeasday** [comment]
@jedwards1211 - http://guide.meteor.com/v1.3/react.html#using-createContainer

**Comment by ffxsam** [comment]
Oh wow! And here I just suggested to my team that we keep using the `ReactMeteorData` mixin until MDG had a more official stance on what to use. :)

**Comment by ffxsam** [comment]
@tmeasday What if we wanted to also wire in Redux? Would this work?

```javascript
import { connect } from 'react-redux';

// ...
const ListsShowContainer = createContainer({ params } => {
  const { id } = params;
  const todosHandle = Meteor.subscribe('todos.inList', id);
  const loading = !todosHandle.ready();
  const list = Lists.findOne(id);
  const listExists = !loading && !!list;
  return {
    loading,
    list,
    listExists,
    todos: listExists ? list.todos().fetch() : [],
  };
}, ListsShow);

export default connect(state => ({ stuff: state.stuff }))(ListsShowContainer)
```

**Comment by stubailo** [comment]
Yes it would! You could also use that Redux state in your Meteor container through the props.

**Comment by ffxsam** [comment]
You mean like this?

```javascript
const ListsShowContainer = connect(state => ({ stuff: state.stuff }))(createContainer({ stuff, params } => {
  const { id } = params;
  const todosHandle = Meteor.subscribe('todos.inList', id);
  const loading = !todosHandle.ready();
  const list = Lists.findOne(id);
  const listExists = !loading && !!list;
  return {
    loading,
    list,
    listExists,
    todos: listExists ? list.todos().fetch() : [],
    stuff,
  };
}, ListsShow));
```

**Comment by stubailo** [comment]
Yes you can do that, I was also thinking you could use `stuff` to filter your minimongo query or as an argument into your subscription, which would let you use client-side state to filter your server-side data.

**Comment by ffxsam** [comment]
Ah, that's a great idea, thanks!
