### ISSUE TITLE
displayName is not inferred

### ISSUE THREAD

**Issue by Sanjo** [meteor/react-packages#81]
The current release of the package doesn't infer display names.

See: https://facebook.github.io/react/docs/jsx-in-depth.html#the-transform
It also works on babeljs.io. See [this example](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=Leaderboard%20%3D%20React.createClass(%7B%0A%20%20getInitialState%3A%20function%20()%20%7B%0A%20%20%20%20return%20%7B%0A%20%20%20%20%20%20selectedPlayerId%3A%20null%0A%20%20%20%20%7D%0A%20%20%7D%2C%0A%0A%20%20render()%20%7B%0A%20%20%20%20var%20createPlayer%20%3D%20(player)%20%3D%3E%20%7B%0A%20%20%20%20%20%20return%20(%0A%20%20%20%20%20%20%20%20%3CPlayer%20%7B...player%7D%0A%20%20%20%20%20%20%20%20%20%20key%3D%7Bplayer._id%7D%0A%20%20%20%20%20%20%20%20%20%20selected%3D%7Bplayer._id%20%26%26%20player._id%20%3D%3D%3D%20this.state.selectedPlayerId%7D%0A%20%20%20%20%20%20%20%20%20%20onSelect%3D%7Bthis.onSelectPlayer%7D%0A%20%20%20%20%20%20%20%20%2F%3E%0A%20%20%20%20%20%20)%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3Col%20className%3D%22leaderboard%22%3E%0A%20%20%20%20%20%20%20%20%7Bthis.props.players.map(createPlayer)%7D%0A%20%20%20%20%20%20%3C%2Fol%3E%0A%20%20%20%20)%3B%0A%20%20%7D%2C%0A%0A%20%20onSelectPlayer(player)%20%7B%0A%20%20%20%20this.setState(%7BselectedPlayerId%3A%20player._id%7D)%3B%0A%20%20%7D%0A%7D)%0A).

This can be reproduces with the react-todos example.

Having this would be very helpful for debugging. E.g using the React developer tools for Chrome.

**Comment by stubailo** [comment]
@dgreensp I was pretty sure we identified and then fixed this bug in a new release of the `jsx` package. Have you tried the newest version?

**Comment by Sanjo** [comment]
Works in the latest published version. I missed that there is a newer version, because it is not pushed to this repository yet (https://github.com/meteor/react-packages/blob/master/packages/jsx/package.js#L4). After updating jsx from 0.1.3 to 0.1.5 it works.

**Comment by stubailo** [comment]
Awesome. Yeah we had some issues with not pushing version numbers.

**Comment by Jpunt** [comment]
@Sanjo: How did you install 0.1.5? When I update with `meteor update jsx` it installs, but it jumps back to 0.1.2 after a second or so.

**Comment by Sanjo** [comment]
@Jpunt Maybe you need to stop your app before or you have a version constraint for jsx in .meteor/packages? You can fix the version with `meteor add jsx@0.1.5`. In my case it just worked with `meteor update jsx` when I remember correctly.

**Comment by Jpunt** [comment]
Stopping the server before updating did the trick. Thanks, i'm kinda new in the meteor-world.
