### ISSUE TITLE
Problem installing 0.1.9

### ISSUE THREAD

**Issue by mhhf** [meteor/react-packages#87]
```
$ meteor --version
Meteor 1.1.0.3
$ meteor create test
$ cd test
$ meteor add react@0.1.9
=> Errors while adding packages:

While selecting package versions:
error: Conflict: Constraint react-runtime@0.13.3_5 is not satisfied by react-runtime 0.13.3.
Constraints on package "react-runtime":
* react-runtime@0.13.3_5 <- react 0.1.9
```

Am I missing something?

**Comment by stubailo** [comment]
@dgreensp any thoughts? This is similar to the error I ran into when publishing.

**Comment by SenerDemiral** [comment]
React versions:
meteor add react -> load react 0.1.7
atmosphere shows 0.1.9
react-packages/packages/react/package.js shows 0.1.8

**Comment by SenerDemiral** [comment]
After version changed to 0.1.9, still same arror.
$ meteor add react@0.1.9
 => Errors while adding packages:             
                                              
While selecting package versions:
error: Conflict: Constraint react-runtime-prod@=0.13.3_3 is not satisfied by
react-runtime-prod 0.13.3_2.
Constraints on package "react-runtime-prod":
* react-runtime-prod@=0.13.3_3 <- react-runtime 0.13.3_5 <- react 0.1.9

**Comment by dgreensp** [comment]
@SenerDemiral The latest published version of `react` doesn't work with Meteor 1.1.x.  You'll need to run with `--release METEOR@1.2-rc.3` to use it.

**Comment by rclai** [comment]
Has it been announced somewhere that we can test out the [1.2 RCs](https://github.com/meteor/meteor/releases)?

**Comment by dgreensp** [comment]
No, but that's coming next week.

There's a placeholder issue here: https://github.com/meteor/meteor/issues/4943

**Comment by rclai** [comment]
Oh ok cool.

**Comment by SenerDemiral** [comment]
meteor --release METEOR@1.2-rc.3
meteor add react@0.1.9
still same error..
=> Errors while adding packages:

While selecting package versions:
error: Conflict: Constraint react-runtime-prod@=0.13.3_3 is not satisfied by
react-runtime-prod 0.13.3_2.
Constraints on package "react-runtime-prod":

    react-runtime-prod@=0.13.3_3 <- react-runtime 0.13.3_5 <- react 0.1.9

**Comment by dgreensp** [comment]
To change your app's Meteor release (in `.meteor/release`), use `meteor update --release METEOR@1.2-rc.3`.

**Comment by SenerDemiral** [comment]
Sory!

**Comment by SenerDemiral** [comment]
After upgrade to 1.2-rc.3
In Todos example
Icons (New List, Make List Private, Delete List and Done) disappeared! (Changed to empty rectangle)

**Comment by dgreensp** [comment]
Ah, shoot.  If you add the `standard-minifiers` package to your app, it will fix it.  This package is supposed to be added to your app automatically when you upgrade.  (It's the code that concatenates your CSS together, pulled out of the tool into a package that is removable.)

**Comment by SenerDemiral** [comment]
Thanks. Icons came back!
