### ISSUE TITLE
Question: is it possible to integrate webpack for live editing during development

### ISSUE THREAD

**Issue by Aaron2Ti** [meteor/react-packages#89]
As introduced in the following video,  the react-hot-loader is a useful tool while doing prototyping,
is it possible to leverage it with meteor?

https://www.youtube.com/watch?v=pw4fKkyPPg8

**Comment by AdamBrodzinski** [comment]
Yes! but not directly with Meteor (unless that's coming in the reloading system?). You have to essentially run it outside of meteor and then have webpack drop the compiled `client.main.js` & `server.main.js`  filess into the client/server directories. 

You can use Meteor packages as well... you just have to add them and then assume they're available globally like normal. Local code is required with ES6 modules.

Checkout this repo: https://github.com/jedwards1211/meteor-webpack-react 

react-hot-loader is pre configured. You'll also get ES6 modules so there is no longer an issue with file loading order :smiley: I've been using it a while on a new project and it's really nice... especially with the Redux time travel debugger using hot-loader.

Currently the only things that don't work are server source maps (in the node-inspector debugger) and the meteor shell doesn't allow you to require modules from webpack. They're on the todo list but overall the pros are greater.

**Comment by Aaron2Ti** [comment]
wow, cool, thanks for the quick reply, will play with it later this week
