### ISSUE TITLE
externalify documentation needs update

### ISSUE THREAD

**Issue by markoshust** [meteor/react-packages#94]
Noticed on this page https://github.com/meteor/react-packages/blob/devel/docs/client-npm.md

this:

    {
      "transforms": {
        "externalify": {
          "global": true,
          "external": {
            "react": "Package['react-runtime'].React.require"
          }
        }
      }
    }

needs to be updated to this:

    {
      "transforms": {
        "externalify": {
          "global": true,
          "external": {
            "react": "React.require"
          }
        }
      }
    }

**Comment by stubailo** [comment]
@markoshust this is actually the _new_ version that I updated recently - does it not work for you?

**Comment by SenerDemiral** [comment]
It is not working on todos example. (1.2.0.rc7)
```
"react": "Package['react-runtime'].React.require"
```

**Comment by artin-phares** [comment]
+1 misleading doc http://react-in-meteor.readthedocs.org/en/latest/client-npm/
Using <code>"react": "React.require"</code> for now.

**Comment by broberts4** [comment]
Same as @SenerDemiral and @artin-phares (i.e., build breaks) w/ 

- Meteor 1.1.0.3
- react 0.1.10

**Comment by stubailo** [comment]
OK put it back to the way it was.
