### ISSUE TITLE
ReactTodos example mistake.

### ISSUE THREAD

**Issue by SenerDemiral** [meteor/react-packages#96]
/examples/react-todos/client/components/todo-list/TodoListHeader.jsx
Line 144
```
 <a className="nav-item" onClick={ this.props.onToggleListPrivacy }>
```
should be
```
 <a className="nav-item" onClick={ this.toggleListPrivacy }>
```

**Comment by stubailo** [comment]
Thanks!

**Comment by benco420** [comment]
Fix is still incorrect (slight typo):

/examples/react-todos/client/components/todo-list/TodoListHeader.jsx
Line 144

    <a className="nav-item" onClick={ this.onToggleListPrivacy }>

should be

    <a className="nav-item" onClick={ this.toggleListPrivacy }>

**Comment by stubailo** [comment]
Crap.
