### ISSUE TITLE
react-todos example: canceling of list title editing doesn't work.

### ISSUE THREAD

**Issue by FranciscoBarros** [meteor/react-packages#98]
client/components/todo-list/TodoListHeader.jsx

When editing title, a Cancel icon is shown on right (line 117), but it's not working.

**Comment by stubailo** [comment]
Interesting - it works for me; what browser are you using?

**Comment by tmeasday** [comment]
Can you reopen at github.com/meteor/todos if you see the same issue on the `react` branch there?

Thanks!
